/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "trace.h"

uint16_t _TRACE_VISIT_FREE_DSTATE;
uint16_t _TRACE_VISIT_COMPLETE_DSTATE;
uint16_t _TRACE_VISIT_START_STRUCT_DSTATE;
uint16_t _TRACE_VISIT_CHECK_STRUCT_DSTATE;
uint16_t _TRACE_VISIT_END_STRUCT_DSTATE;
uint16_t _TRACE_VISIT_START_LIST_DSTATE;
uint16_t _TRACE_VISIT_NEXT_LIST_DSTATE;
uint16_t _TRACE_VISIT_CHECK_LIST_DSTATE;
uint16_t _TRACE_VISIT_END_LIST_DSTATE;
uint16_t _TRACE_VISIT_START_ALTERNATE_DSTATE;
uint16_t _TRACE_VISIT_END_ALTERNATE_DSTATE;
uint16_t _TRACE_VISIT_OPTIONAL_DSTATE;
uint16_t _TRACE_VISIT_TYPE_ENUM_DSTATE;
uint16_t _TRACE_VISIT_TYPE_INT_DSTATE;
uint16_t _TRACE_VISIT_TYPE_UINT8_DSTATE;
uint16_t _TRACE_VISIT_TYPE_UINT16_DSTATE;
uint16_t _TRACE_VISIT_TYPE_UINT32_DSTATE;
uint16_t _TRACE_VISIT_TYPE_UINT64_DSTATE;
uint16_t _TRACE_VISIT_TYPE_INT8_DSTATE;
uint16_t _TRACE_VISIT_TYPE_INT16_DSTATE;
uint16_t _TRACE_VISIT_TYPE_INT32_DSTATE;
uint16_t _TRACE_VISIT_TYPE_INT64_DSTATE;
uint16_t _TRACE_VISIT_TYPE_SIZE_DSTATE;
uint16_t _TRACE_VISIT_TYPE_BOOL_DSTATE;
uint16_t _TRACE_VISIT_TYPE_STR_DSTATE;
uint16_t _TRACE_VISIT_TYPE_NUMBER_DSTATE;
uint16_t _TRACE_VISIT_TYPE_ANY_DSTATE;
uint16_t _TRACE_VISIT_TYPE_NULL_DSTATE;
TraceEvent _TRACE_VISIT_FREE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_free",
    .sstate = TRACE_VISIT_FREE_ENABLED,
    .dstate = &_TRACE_VISIT_FREE_DSTATE 
};
TraceEvent _TRACE_VISIT_COMPLETE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_complete",
    .sstate = TRACE_VISIT_COMPLETE_ENABLED,
    .dstate = &_TRACE_VISIT_COMPLETE_DSTATE 
};
TraceEvent _TRACE_VISIT_START_STRUCT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_start_struct",
    .sstate = TRACE_VISIT_START_STRUCT_ENABLED,
    .dstate = &_TRACE_VISIT_START_STRUCT_DSTATE 
};
TraceEvent _TRACE_VISIT_CHECK_STRUCT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_check_struct",
    .sstate = TRACE_VISIT_CHECK_STRUCT_ENABLED,
    .dstate = &_TRACE_VISIT_CHECK_STRUCT_DSTATE 
};
TraceEvent _TRACE_VISIT_END_STRUCT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_end_struct",
    .sstate = TRACE_VISIT_END_STRUCT_ENABLED,
    .dstate = &_TRACE_VISIT_END_STRUCT_DSTATE 
};
TraceEvent _TRACE_VISIT_START_LIST_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_start_list",
    .sstate = TRACE_VISIT_START_LIST_ENABLED,
    .dstate = &_TRACE_VISIT_START_LIST_DSTATE 
};
TraceEvent _TRACE_VISIT_NEXT_LIST_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_next_list",
    .sstate = TRACE_VISIT_NEXT_LIST_ENABLED,
    .dstate = &_TRACE_VISIT_NEXT_LIST_DSTATE 
};
TraceEvent _TRACE_VISIT_CHECK_LIST_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_check_list",
    .sstate = TRACE_VISIT_CHECK_LIST_ENABLED,
    .dstate = &_TRACE_VISIT_CHECK_LIST_DSTATE 
};
TraceEvent _TRACE_VISIT_END_LIST_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_end_list",
    .sstate = TRACE_VISIT_END_LIST_ENABLED,
    .dstate = &_TRACE_VISIT_END_LIST_DSTATE 
};
TraceEvent _TRACE_VISIT_START_ALTERNATE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_start_alternate",
    .sstate = TRACE_VISIT_START_ALTERNATE_ENABLED,
    .dstate = &_TRACE_VISIT_START_ALTERNATE_DSTATE 
};
TraceEvent _TRACE_VISIT_END_ALTERNATE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_end_alternate",
    .sstate = TRACE_VISIT_END_ALTERNATE_ENABLED,
    .dstate = &_TRACE_VISIT_END_ALTERNATE_DSTATE 
};
TraceEvent _TRACE_VISIT_OPTIONAL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_optional",
    .sstate = TRACE_VISIT_OPTIONAL_ENABLED,
    .dstate = &_TRACE_VISIT_OPTIONAL_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_ENUM_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_enum",
    .sstate = TRACE_VISIT_TYPE_ENUM_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_ENUM_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_INT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_int",
    .sstate = TRACE_VISIT_TYPE_INT_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_INT_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_UINT8_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_uint8",
    .sstate = TRACE_VISIT_TYPE_UINT8_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_UINT8_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_UINT16_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_uint16",
    .sstate = TRACE_VISIT_TYPE_UINT16_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_UINT16_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_UINT32_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_uint32",
    .sstate = TRACE_VISIT_TYPE_UINT32_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_UINT32_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_UINT64_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_uint64",
    .sstate = TRACE_VISIT_TYPE_UINT64_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_UINT64_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_INT8_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_int8",
    .sstate = TRACE_VISIT_TYPE_INT8_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_INT8_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_INT16_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_int16",
    .sstate = TRACE_VISIT_TYPE_INT16_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_INT16_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_INT32_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_int32",
    .sstate = TRACE_VISIT_TYPE_INT32_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_INT32_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_INT64_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_int64",
    .sstate = TRACE_VISIT_TYPE_INT64_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_INT64_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_SIZE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_size",
    .sstate = TRACE_VISIT_TYPE_SIZE_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_SIZE_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_BOOL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_bool",
    .sstate = TRACE_VISIT_TYPE_BOOL_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_BOOL_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_STR_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_str",
    .sstate = TRACE_VISIT_TYPE_STR_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_STR_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_NUMBER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_number",
    .sstate = TRACE_VISIT_TYPE_NUMBER_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_NUMBER_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_ANY_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_any",
    .sstate = TRACE_VISIT_TYPE_ANY_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_ANY_DSTATE 
};
TraceEvent _TRACE_VISIT_TYPE_NULL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "visit_type_null",
    .sstate = TRACE_VISIT_TYPE_NULL_ENABLED,
    .dstate = &_TRACE_VISIT_TYPE_NULL_DSTATE 
};
TraceEvent *qapi_trace_events[] = {
    &_TRACE_VISIT_FREE_EVENT,
    &_TRACE_VISIT_COMPLETE_EVENT,
    &_TRACE_VISIT_START_STRUCT_EVENT,
    &_TRACE_VISIT_CHECK_STRUCT_EVENT,
    &_TRACE_VISIT_END_STRUCT_EVENT,
    &_TRACE_VISIT_START_LIST_EVENT,
    &_TRACE_VISIT_NEXT_LIST_EVENT,
    &_TRACE_VISIT_CHECK_LIST_EVENT,
    &_TRACE_VISIT_END_LIST_EVENT,
    &_TRACE_VISIT_START_ALTERNATE_EVENT,
    &_TRACE_VISIT_END_ALTERNATE_EVENT,
    &_TRACE_VISIT_OPTIONAL_EVENT,
    &_TRACE_VISIT_TYPE_ENUM_EVENT,
    &_TRACE_VISIT_TYPE_INT_EVENT,
    &_TRACE_VISIT_TYPE_UINT8_EVENT,
    &_TRACE_VISIT_TYPE_UINT16_EVENT,
    &_TRACE_VISIT_TYPE_UINT32_EVENT,
    &_TRACE_VISIT_TYPE_UINT64_EVENT,
    &_TRACE_VISIT_TYPE_INT8_EVENT,
    &_TRACE_VISIT_TYPE_INT16_EVENT,
    &_TRACE_VISIT_TYPE_INT32_EVENT,
    &_TRACE_VISIT_TYPE_INT64_EVENT,
    &_TRACE_VISIT_TYPE_SIZE_EVENT,
    &_TRACE_VISIT_TYPE_BOOL_EVENT,
    &_TRACE_VISIT_TYPE_STR_EVENT,
    &_TRACE_VISIT_TYPE_NUMBER_EVENT,
    &_TRACE_VISIT_TYPE_ANY_EVENT,
    &_TRACE_VISIT_TYPE_NULL_EVENT,
  NULL,
};

static void trace_qapi_register_events(void)
{
    trace_event_register_group(qapi_trace_events);
}
trace_init(trace_qapi_register_events)
