/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "trace.h"

uint16_t _TRACE_WCT_INIT_DSTATE;
uint16_t _TRACE_WCT_CMD_RE_DSTATE;
uint16_t _TRACE_WCT_CMD_ST_DSTATE;
uint16_t _TRACE_WCT_CMD_SP_DSTATE;
uint16_t _TRACE_WCT_CMD_TS_DSTATE;
uint16_t _TRACE_WCT_CMD_OTHER_DSTATE;
uint16_t _TRACE_WCT_SPEED_DSTATE;
TraceEvent _TRACE_WCT_INIT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "wct_init",
    .sstate = TRACE_WCT_INIT_ENABLED,
    .dstate = &_TRACE_WCT_INIT_DSTATE 
};
TraceEvent _TRACE_WCT_CMD_RE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "wct_cmd_re",
    .sstate = TRACE_WCT_CMD_RE_ENABLED,
    .dstate = &_TRACE_WCT_CMD_RE_DSTATE 
};
TraceEvent _TRACE_WCT_CMD_ST_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "wct_cmd_st",
    .sstate = TRACE_WCT_CMD_ST_ENABLED,
    .dstate = &_TRACE_WCT_CMD_ST_DSTATE 
};
TraceEvent _TRACE_WCT_CMD_SP_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "wct_cmd_sp",
    .sstate = TRACE_WCT_CMD_SP_ENABLED,
    .dstate = &_TRACE_WCT_CMD_SP_DSTATE 
};
TraceEvent _TRACE_WCT_CMD_TS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "wct_cmd_ts",
    .sstate = TRACE_WCT_CMD_TS_ENABLED,
    .dstate = &_TRACE_WCT_CMD_TS_DSTATE 
};
TraceEvent _TRACE_WCT_CMD_OTHER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "wct_cmd_other",
    .sstate = TRACE_WCT_CMD_OTHER_ENABLED,
    .dstate = &_TRACE_WCT_CMD_OTHER_DSTATE 
};
TraceEvent _TRACE_WCT_SPEED_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "wct_speed",
    .sstate = TRACE_WCT_SPEED_ENABLED,
    .dstate = &_TRACE_WCT_SPEED_DSTATE 
};
TraceEvent *backends_trace_events[] = {
    &_TRACE_WCT_INIT_EVENT,
    &_TRACE_WCT_CMD_RE_EVENT,
    &_TRACE_WCT_CMD_ST_EVENT,
    &_TRACE_WCT_CMD_SP_EVENT,
    &_TRACE_WCT_CMD_TS_EVENT,
    &_TRACE_WCT_CMD_OTHER_EVENT,
    &_TRACE_WCT_SPEED_EVENT,
  NULL,
};

static void trace_backends_register_events(void)
{
    trace_event_register_group(backends_trace_events);
}
trace_init(trace_backends_register_events)
