/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_BLOCK_DATAPLANE_GENERATED_TRACERS_H
#define TRACE_HW_BLOCK_DATAPLANE_GENERATED_TRACERS_H

#include "qemu-common.h"
#include "trace/control.h"

extern TraceEvent _TRACE_VIRTIO_BLK_DATA_PLANE_START_EVENT;
extern TraceEvent _TRACE_VIRTIO_BLK_DATA_PLANE_STOP_EVENT;
extern uint16_t _TRACE_VIRTIO_BLK_DATA_PLANE_START_DSTATE;
extern uint16_t _TRACE_VIRTIO_BLK_DATA_PLANE_STOP_DSTATE;
#define TRACE_VIRTIO_BLK_DATA_PLANE_START_ENABLED 1
#define TRACE_VIRTIO_BLK_DATA_PLANE_STOP_ENABLED 1
#include "qemu/log.h"


static inline void trace_virtio_blk_data_plane_start(void * s)
{
    if (true) {
        if (trace_event_get_state(TRACE_VIRTIO_BLK_DATA_PLANE_START)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:virtio_blk_data_plane_start " "dataplane %p" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , s);
        }
    }
}

static inline void trace_virtio_blk_data_plane_stop(void * s)
{
    if (true) {
        if (trace_event_get_state(TRACE_VIRTIO_BLK_DATA_PLANE_STOP)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:virtio_blk_data_plane_stop " "dataplane %p" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , s);
        }
    }
}
#endif /* TRACE_HW_BLOCK_DATAPLANE_GENERATED_TRACERS_H */
