/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_9PFS_GENERATED_TRACERS_H
#define TRACE_HW_9PFS_GENERATED_TRACERS_H

#include "qemu-common.h"
#include "trace/control.h"

extern TraceEvent _TRACE_V9FS_RERROR_EVENT;
extern TraceEvent _TRACE_V9FS_VERSION_EVENT;
extern TraceEvent _TRACE_V9FS_VERSION_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_ATTACH_EVENT;
extern TraceEvent _TRACE_V9FS_ATTACH_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_STAT_EVENT;
extern TraceEvent _TRACE_V9FS_STAT_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_GETATTR_EVENT;
extern TraceEvent _TRACE_V9FS_GETATTR_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_WALK_EVENT;
extern TraceEvent _TRACE_V9FS_WALK_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_OPEN_EVENT;
extern TraceEvent _TRACE_V9FS_OPEN_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_LCREATE_EVENT;
extern TraceEvent _TRACE_V9FS_LCREATE_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_FSYNC_EVENT;
extern TraceEvent _TRACE_V9FS_CLUNK_EVENT;
extern TraceEvent _TRACE_V9FS_READ_EVENT;
extern TraceEvent _TRACE_V9FS_READ_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_READDIR_EVENT;
extern TraceEvent _TRACE_V9FS_READDIR_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_WRITE_EVENT;
extern TraceEvent _TRACE_V9FS_WRITE_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_CREATE_EVENT;
extern TraceEvent _TRACE_V9FS_CREATE_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_SYMLINK_EVENT;
extern TraceEvent _TRACE_V9FS_SYMLINK_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_FLUSH_EVENT;
extern TraceEvent _TRACE_V9FS_LINK_EVENT;
extern TraceEvent _TRACE_V9FS_REMOVE_EVENT;
extern TraceEvent _TRACE_V9FS_WSTAT_EVENT;
extern TraceEvent _TRACE_V9FS_MKNOD_EVENT;
extern TraceEvent _TRACE_V9FS_MKNOD_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_LOCK_EVENT;
extern TraceEvent _TRACE_V9FS_LOCK_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_GETLOCK_EVENT;
extern TraceEvent _TRACE_V9FS_GETLOCK_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_MKDIR_EVENT;
extern TraceEvent _TRACE_V9FS_MKDIR_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_XATTRWALK_EVENT;
extern TraceEvent _TRACE_V9FS_XATTRWALK_RETURN_EVENT;
extern TraceEvent _TRACE_V9FS_XATTRCREATE_EVENT;
extern TraceEvent _TRACE_V9FS_READLINK_EVENT;
extern TraceEvent _TRACE_V9FS_READLINK_RETURN_EVENT;
extern uint16_t _TRACE_V9FS_RERROR_DSTATE;
extern uint16_t _TRACE_V9FS_VERSION_DSTATE;
extern uint16_t _TRACE_V9FS_VERSION_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_ATTACH_DSTATE;
extern uint16_t _TRACE_V9FS_ATTACH_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_STAT_DSTATE;
extern uint16_t _TRACE_V9FS_STAT_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_GETATTR_DSTATE;
extern uint16_t _TRACE_V9FS_GETATTR_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_WALK_DSTATE;
extern uint16_t _TRACE_V9FS_WALK_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_OPEN_DSTATE;
extern uint16_t _TRACE_V9FS_OPEN_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_LCREATE_DSTATE;
extern uint16_t _TRACE_V9FS_LCREATE_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_FSYNC_DSTATE;
extern uint16_t _TRACE_V9FS_CLUNK_DSTATE;
extern uint16_t _TRACE_V9FS_READ_DSTATE;
extern uint16_t _TRACE_V9FS_READ_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_READDIR_DSTATE;
extern uint16_t _TRACE_V9FS_READDIR_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_WRITE_DSTATE;
extern uint16_t _TRACE_V9FS_WRITE_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_CREATE_DSTATE;
extern uint16_t _TRACE_V9FS_CREATE_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_SYMLINK_DSTATE;
extern uint16_t _TRACE_V9FS_SYMLINK_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_FLUSH_DSTATE;
extern uint16_t _TRACE_V9FS_LINK_DSTATE;
extern uint16_t _TRACE_V9FS_REMOVE_DSTATE;
extern uint16_t _TRACE_V9FS_WSTAT_DSTATE;
extern uint16_t _TRACE_V9FS_MKNOD_DSTATE;
extern uint16_t _TRACE_V9FS_MKNOD_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_LOCK_DSTATE;
extern uint16_t _TRACE_V9FS_LOCK_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_GETLOCK_DSTATE;
extern uint16_t _TRACE_V9FS_GETLOCK_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_MKDIR_DSTATE;
extern uint16_t _TRACE_V9FS_MKDIR_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_XATTRWALK_DSTATE;
extern uint16_t _TRACE_V9FS_XATTRWALK_RETURN_DSTATE;
extern uint16_t _TRACE_V9FS_XATTRCREATE_DSTATE;
extern uint16_t _TRACE_V9FS_READLINK_DSTATE;
extern uint16_t _TRACE_V9FS_READLINK_RETURN_DSTATE;
#define TRACE_V9FS_RERROR_ENABLED 1
#define TRACE_V9FS_VERSION_ENABLED 1
#define TRACE_V9FS_VERSION_RETURN_ENABLED 1
#define TRACE_V9FS_ATTACH_ENABLED 1
#define TRACE_V9FS_ATTACH_RETURN_ENABLED 1
#define TRACE_V9FS_STAT_ENABLED 1
#define TRACE_V9FS_STAT_RETURN_ENABLED 1
#define TRACE_V9FS_GETATTR_ENABLED 1
#define TRACE_V9FS_GETATTR_RETURN_ENABLED 1
#define TRACE_V9FS_WALK_ENABLED 1
#define TRACE_V9FS_WALK_RETURN_ENABLED 1
#define TRACE_V9FS_OPEN_ENABLED 1
#define TRACE_V9FS_OPEN_RETURN_ENABLED 1
#define TRACE_V9FS_LCREATE_ENABLED 1
#define TRACE_V9FS_LCREATE_RETURN_ENABLED 1
#define TRACE_V9FS_FSYNC_ENABLED 1
#define TRACE_V9FS_CLUNK_ENABLED 1
#define TRACE_V9FS_READ_ENABLED 1
#define TRACE_V9FS_READ_RETURN_ENABLED 1
#define TRACE_V9FS_READDIR_ENABLED 1
#define TRACE_V9FS_READDIR_RETURN_ENABLED 1
#define TRACE_V9FS_WRITE_ENABLED 1
#define TRACE_V9FS_WRITE_RETURN_ENABLED 1
#define TRACE_V9FS_CREATE_ENABLED 1
#define TRACE_V9FS_CREATE_RETURN_ENABLED 1
#define TRACE_V9FS_SYMLINK_ENABLED 1
#define TRACE_V9FS_SYMLINK_RETURN_ENABLED 1
#define TRACE_V9FS_FLUSH_ENABLED 1
#define TRACE_V9FS_LINK_ENABLED 1
#define TRACE_V9FS_REMOVE_ENABLED 1
#define TRACE_V9FS_WSTAT_ENABLED 1
#define TRACE_V9FS_MKNOD_ENABLED 1
#define TRACE_V9FS_MKNOD_RETURN_ENABLED 1
#define TRACE_V9FS_LOCK_ENABLED 1
#define TRACE_V9FS_LOCK_RETURN_ENABLED 1
#define TRACE_V9FS_GETLOCK_ENABLED 1
#define TRACE_V9FS_GETLOCK_RETURN_ENABLED 1
#define TRACE_V9FS_MKDIR_ENABLED 1
#define TRACE_V9FS_MKDIR_RETURN_ENABLED 1
#define TRACE_V9FS_XATTRWALK_ENABLED 1
#define TRACE_V9FS_XATTRWALK_RETURN_ENABLED 1
#define TRACE_V9FS_XATTRCREATE_ENABLED 1
#define TRACE_V9FS_READLINK_ENABLED 1
#define TRACE_V9FS_READLINK_RETURN_ENABLED 1
#include "qemu/log.h"


static inline void trace_v9fs_rerror(uint16_t tag, uint8_t id, int err)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_RERROR)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_rerror " "tag %d id %d err %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, err);
        }
    }
}

static inline void trace_v9fs_version(uint16_t tag, uint8_t id, int32_t msize, char* version)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_VERSION)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_version " "tag %d id %d msize %d version %s" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, msize, version);
        }
    }
}

static inline void trace_v9fs_version_return(uint16_t tag, uint8_t id, int32_t msize, char* version)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_VERSION_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_version_return " "tag %d id %d msize %d version %s" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, msize, version);
        }
    }
}

static inline void trace_v9fs_attach(uint16_t tag, uint8_t id, int32_t fid, int32_t afid, char* uname, char* aname)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_ATTACH)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_attach " "tag %u id %u fid %d afid %d uname %s aname %s" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, afid, uname, aname);
        }
    }
}

static inline void trace_v9fs_attach_return(uint16_t tag, uint8_t id, int8_t type, int32_t version, int64_t path)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_ATTACH_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_attach_return " "tag %d id %d type %d version %d path %"PRId64 "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, type, version, path);
        }
    }
}

static inline void trace_v9fs_stat(uint16_t tag, uint8_t id, int32_t fid)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_STAT)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_stat " "tag %d id %d fid %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid);
        }
    }
}

static inline void trace_v9fs_stat_return(uint16_t tag, uint8_t id, int32_t mode, int32_t atime, int32_t mtime, int64_t length)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_STAT_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_stat_return " "tag %d id %d stat={mode %d atime %d mtime %d length %"PRId64"}" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, mode, atime, mtime, length);
        }
    }
}

static inline void trace_v9fs_getattr(uint16_t tag, uint8_t id, int32_t fid, uint64_t request_mask)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_GETATTR)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_getattr " "tag %d id %d fid %d request_mask %"PRIu64 "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, request_mask);
        }
    }
}

static inline void trace_v9fs_getattr_return(uint16_t tag, uint8_t id, uint64_t result_mask, uint32_t mode, uint32_t uid, uint32_t gid)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_GETATTR_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_getattr_return " "tag %d id %d getattr={result_mask %"PRId64" mode %u uid %u gid %u}" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, result_mask, mode, uid, gid);
        }
    }
}

static inline void trace_v9fs_walk(uint16_t tag, uint8_t id, int32_t fid, int32_t newfid, uint16_t nwnames)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_WALK)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_walk " "tag %d id %d fid %d newfid %d nwnames %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, newfid, nwnames);
        }
    }
}

static inline void trace_v9fs_walk_return(uint16_t tag, uint8_t id, uint16_t nwnames, void* qids)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_WALK_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_walk_return " "tag %d id %d nwnames %d qids %p" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, nwnames, qids);
        }
    }
}

static inline void trace_v9fs_open(uint16_t tag, uint8_t id, int32_t fid, int32_t mode)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_OPEN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_open " "tag %d id %d fid %d mode %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, mode);
        }
    }
}

static inline void trace_v9fs_open_return(uint16_t tag, uint8_t id, int8_t type, int32_t version, int64_t path, int iounit)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_OPEN_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_open_return " "tag %d id %d qid={type %d version %d path %"PRId64"} iounit %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, type, version, path, iounit);
        }
    }
}

static inline void trace_v9fs_lcreate(uint16_t tag, uint8_t id, int32_t dfid, int32_t flags, int32_t mode, uint32_t gid)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_LCREATE)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_lcreate " "tag %d id %d dfid %d flags %d mode %d gid %u" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, dfid, flags, mode, gid);
        }
    }
}

static inline void trace_v9fs_lcreate_return(uint16_t tag, uint8_t id, int8_t type, int32_t version, int64_t path, int32_t iounit)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_LCREATE_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_lcreate_return " "tag %d id %d qid={type %d version %d path %"PRId64"} iounit %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, type, version, path, iounit);
        }
    }
}

static inline void trace_v9fs_fsync(uint16_t tag, uint8_t id, int32_t fid, int datasync)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_FSYNC)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_fsync " "tag %d id %d fid %d datasync %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, datasync);
        }
    }
}

static inline void trace_v9fs_clunk(uint16_t tag, uint8_t id, int32_t fid)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_CLUNK)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_clunk " "tag %d id %d fid %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid);
        }
    }
}

static inline void trace_v9fs_read(uint16_t tag, uint8_t id, int32_t fid, uint64_t off, uint32_t max_count)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_READ)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_read " "tag %d id %d fid %d off %"PRIu64" max_count %u" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, off, max_count);
        }
    }
}

static inline void trace_v9fs_read_return(uint16_t tag, uint8_t id, int32_t count, ssize_t err)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_READ_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_read_return " "tag %d id %d count %d err %zd" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, count, err);
        }
    }
}

static inline void trace_v9fs_readdir(uint16_t tag, uint8_t id, int32_t fid, uint64_t offset, uint32_t max_count)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_READDIR)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_readdir " "tag %d id %d fid %d offset %"PRIu64" max_count %u" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, offset, max_count);
        }
    }
}

static inline void trace_v9fs_readdir_return(uint16_t tag, uint8_t id, uint32_t count, ssize_t retval)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_READDIR_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_readdir_return " "tag %d id %d count %u retval %zd" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, count, retval);
        }
    }
}

static inline void trace_v9fs_write(uint16_t tag, uint8_t id, int32_t fid, uint64_t off, uint32_t count, int cnt)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_WRITE)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_write " "tag %d id %d fid %d off %"PRIu64" count %u cnt %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, off, count, cnt);
        }
    }
}

static inline void trace_v9fs_write_return(uint16_t tag, uint8_t id, int32_t total, ssize_t err)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_WRITE_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_write_return " "tag %d id %d total %d err %zd" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, total, err);
        }
    }
}

static inline void trace_v9fs_create(uint16_t tag, uint8_t id, int32_t fid, char* name, int32_t perm, int8_t mode)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_CREATE)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_create " "tag %d id %d fid %d name %s perm %d mode %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, name, perm, mode);
        }
    }
}

static inline void trace_v9fs_create_return(uint16_t tag, uint8_t id, int8_t type, int32_t version, int64_t path, int iounit)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_CREATE_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_create_return " "tag %d id %d qid={type %d version %d path %"PRId64"} iounit %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, type, version, path, iounit);
        }
    }
}

static inline void trace_v9fs_symlink(uint16_t tag, uint8_t id, int32_t fid, char* name, char* symname, uint32_t gid)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_SYMLINK)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_symlink " "tag %d id %d fid %d name %s symname %s gid %u" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, name, symname, gid);
        }
    }
}

static inline void trace_v9fs_symlink_return(uint16_t tag, uint8_t id, int8_t type, int32_t version, int64_t path)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_SYMLINK_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_symlink_return " "tag %d id %d qid={type %d version %d path %"PRId64"}" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, type, version, path);
        }
    }
}

static inline void trace_v9fs_flush(uint16_t tag, uint8_t id, int16_t flush_tag)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_FLUSH)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_flush " "tag %d id %d flush_tag %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, flush_tag);
        }
    }
}

static inline void trace_v9fs_link(uint16_t tag, uint8_t id, int32_t dfid, int32_t oldfid, char* name)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_LINK)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_link " "tag %d id %d dfid %d oldfid %d name %s" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, dfid, oldfid, name);
        }
    }
}

static inline void trace_v9fs_remove(uint16_t tag, uint8_t id, int32_t fid)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_REMOVE)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_remove " "tag %d id %d fid %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid);
        }
    }
}

static inline void trace_v9fs_wstat(uint16_t tag, uint8_t id, int32_t fid, int32_t mode, int32_t atime, int32_t mtime)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_WSTAT)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_wstat " "tag %u id %u fid %d stat={mode %d atime %d mtime %d}" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, mode, atime, mtime);
        }
    }
}

static inline void trace_v9fs_mknod(uint16_t tag, uint8_t id, int32_t fid, int mode, int major, int minor)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_MKNOD)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_mknod " "tag %d id %d fid %d mode %d major %d minor %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, mode, major, minor);
        }
    }
}

static inline void trace_v9fs_mknod_return(uint16_t tag, uint8_t id, int8_t type, int32_t version, int64_t path)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_MKNOD_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_mknod_return " "tag %d id %d qid={type %d version %d path %"PRId64"}" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, type, version, path);
        }
    }
}

static inline void trace_v9fs_lock(uint16_t tag, uint8_t id, int32_t fid, uint8_t type, uint64_t start, uint64_t length)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_LOCK)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_lock " "tag %d id %d fid %d type %d start %"PRIu64" length %"PRIu64 "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, type, start, length);
        }
    }
}

static inline void trace_v9fs_lock_return(uint16_t tag, uint8_t id, int8_t status)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_LOCK_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_lock_return " "tag %d id %d status %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, status);
        }
    }
}

static inline void trace_v9fs_getlock(uint16_t tag, uint8_t id, int32_t fid, uint8_t type, uint64_t start, uint64_t length)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_GETLOCK)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_getlock " "tag %d id %d fid %d type %d start %"PRIu64" length %"PRIu64 "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, type, start, length);
        }
    }
}

static inline void trace_v9fs_getlock_return(uint16_t tag, uint8_t id, uint8_t type, uint64_t start, uint64_t length, uint32_t proc_id)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_GETLOCK_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_getlock_return " "tag %d id %d type %d start %"PRIu64" length %"PRIu64" proc_id %u" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, type, start, length, proc_id);
        }
    }
}

static inline void trace_v9fs_mkdir(uint16_t tag, uint8_t id, int32_t fid, char* name, int mode, uint32_t gid)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_MKDIR)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_mkdir " "tag %u id %u fid %d name %s mode %d gid %u" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, name, mode, gid);
        }
    }
}

static inline void trace_v9fs_mkdir_return(uint16_t tag, uint8_t id, int8_t type, int32_t version, int64_t path, int err)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_MKDIR_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_mkdir_return " "tag %u id %u qid={type %d version %d path %"PRId64"} err %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, type, version, path, err);
        }
    }
}

static inline void trace_v9fs_xattrwalk(uint16_t tag, uint8_t id, int32_t fid, int32_t newfid, char* name)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_XATTRWALK)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_xattrwalk " "tag %d id %d fid %d newfid %d name %s" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, newfid, name);
        }
    }
}

static inline void trace_v9fs_xattrwalk_return(uint16_t tag, uint8_t id, int64_t size)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_XATTRWALK_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_xattrwalk_return " "tag %d id %d size %"PRId64 "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, size);
        }
    }
}

static inline void trace_v9fs_xattrcreate(uint16_t tag, uint8_t id, int32_t fid, char* name, uint64_t size, int flags)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_XATTRCREATE)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_xattrcreate " "tag %d id %d fid %d name %s size %"PRIu64" flags %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid, name, size, flags);
        }
    }
}

static inline void trace_v9fs_readlink(uint16_t tag, uint8_t id, int32_t fid)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_READLINK)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_readlink " "tag %d id %d fid %d" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, fid);
        }
    }
}

static inline void trace_v9fs_readlink_return(uint16_t tag, uint8_t id, char* target)
{
    if (true) {
        if (trace_event_get_state(TRACE_V9FS_READLINK_RETURN)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:v9fs_readlink_return " "tag %d id %d name %s" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          , tag, id, target);
        }
    }
}
#endif /* TRACE_HW_9PFS_GENERATED_TRACERS_H */
