/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "trace.h"

uint16_t _TRACE_BDRV_OPEN_COMMON_DSTATE;
uint16_t _TRACE_BDRV_LOCK_MEDIUM_DSTATE;
uint16_t _TRACE_BLK_CO_PREADV_DSTATE;
uint16_t _TRACE_BLK_CO_PWRITEV_DSTATE;
uint16_t _TRACE_BDRV_AIO_FLUSH_DSTATE;
uint16_t _TRACE_BDRV_AIO_READV_DSTATE;
uint16_t _TRACE_BDRV_AIO_WRITEV_DSTATE;
uint16_t _TRACE_BDRV_CO_READV_DSTATE;
uint16_t _TRACE_BDRV_CO_WRITEV_DSTATE;
uint16_t _TRACE_BDRV_CO_PWRITE_ZEROES_DSTATE;
uint16_t _TRACE_BDRV_CO_DO_COPY_ON_READV_DSTATE;
uint16_t _TRACE_STREAM_ONE_ITERATION_DSTATE;
uint16_t _TRACE_STREAM_START_DSTATE;
uint16_t _TRACE_COMMIT_ONE_ITERATION_DSTATE;
uint16_t _TRACE_COMMIT_START_DSTATE;
uint16_t _TRACE_MIRROR_START_DSTATE;
uint16_t _TRACE_MIRROR_RESTART_ITER_DSTATE;
uint16_t _TRACE_MIRROR_BEFORE_FLUSH_DSTATE;
uint16_t _TRACE_MIRROR_BEFORE_DRAIN_DSTATE;
uint16_t _TRACE_MIRROR_BEFORE_SLEEP_DSTATE;
uint16_t _TRACE_MIRROR_ONE_ITERATION_DSTATE;
uint16_t _TRACE_MIRROR_ITERATION_DONE_DSTATE;
uint16_t _TRACE_MIRROR_YIELD_DSTATE;
uint16_t _TRACE_MIRROR_YIELD_IN_FLIGHT_DSTATE;
uint16_t _TRACE_BACKUP_DO_COW_ENTER_DSTATE;
uint16_t _TRACE_BACKUP_DO_COW_RETURN_DSTATE;
uint16_t _TRACE_BACKUP_DO_COW_SKIP_DSTATE;
uint16_t _TRACE_BACKUP_DO_COW_PROCESS_DSTATE;
uint16_t _TRACE_BACKUP_DO_COW_READ_FAIL_DSTATE;
uint16_t _TRACE_BACKUP_DO_COW_WRITE_FAIL_DSTATE;
uint16_t _TRACE_QMP_BLOCK_JOB_CANCEL_DSTATE;
uint16_t _TRACE_QMP_BLOCK_JOB_PAUSE_DSTATE;
uint16_t _TRACE_QMP_BLOCK_JOB_RESUME_DSTATE;
uint16_t _TRACE_QMP_BLOCK_JOB_COMPLETE_DSTATE;
uint16_t _TRACE_QMP_BLOCK_STREAM_DSTATE;
uint16_t _TRACE_PAIO_SUBMIT_CO_DSTATE;
uint16_t _TRACE_PAIO_SUBMIT_DSTATE;
uint16_t _TRACE_QCOW2_WRITEV_START_REQ_DSTATE;
uint16_t _TRACE_QCOW2_WRITEV_DONE_REQ_DSTATE;
uint16_t _TRACE_QCOW2_WRITEV_START_PART_DSTATE;
uint16_t _TRACE_QCOW2_WRITEV_DONE_PART_DSTATE;
uint16_t _TRACE_QCOW2_WRITEV_DATA_DSTATE;
uint16_t _TRACE_QCOW2_PWRITE_ZEROES_START_REQ_DSTATE;
uint16_t _TRACE_QCOW2_PWRITE_ZEROES_DSTATE;
uint16_t _TRACE_QCOW2_ALLOC_CLUSTERS_OFFSET_DSTATE;
uint16_t _TRACE_QCOW2_HANDLE_COPIED_DSTATE;
uint16_t _TRACE_QCOW2_HANDLE_ALLOC_DSTATE;
uint16_t _TRACE_QCOW2_DO_ALLOC_CLUSTERS_OFFSET_DSTATE;
uint16_t _TRACE_QCOW2_CLUSTER_ALLOC_PHYS_DSTATE;
uint16_t _TRACE_QCOW2_CLUSTER_LINK_L2_DSTATE;
uint16_t _TRACE_QCOW2_L2_ALLOCATE_DSTATE;
uint16_t _TRACE_QCOW2_L2_ALLOCATE_GET_EMPTY_DSTATE;
uint16_t _TRACE_QCOW2_L2_ALLOCATE_WRITE_L2_DSTATE;
uint16_t _TRACE_QCOW2_L2_ALLOCATE_WRITE_L1_DSTATE;
uint16_t _TRACE_QCOW2_L2_ALLOCATE_DONE_DSTATE;
uint16_t _TRACE_QCOW2_CACHE_GET_DSTATE;
uint16_t _TRACE_QCOW2_CACHE_GET_REPLACE_ENTRY_DSTATE;
uint16_t _TRACE_QCOW2_CACHE_GET_READ_DSTATE;
uint16_t _TRACE_QCOW2_CACHE_GET_DONE_DSTATE;
uint16_t _TRACE_QCOW2_CACHE_FLUSH_DSTATE;
uint16_t _TRACE_QCOW2_CACHE_ENTRY_FLUSH_DSTATE;
uint16_t _TRACE_QED_ALLOC_L2_CACHE_ENTRY_DSTATE;
uint16_t _TRACE_QED_UNREF_L2_CACHE_ENTRY_DSTATE;
uint16_t _TRACE_QED_FIND_L2_CACHE_ENTRY_DSTATE;
uint16_t _TRACE_QED_READ_TABLE_DSTATE;
uint16_t _TRACE_QED_READ_TABLE_CB_DSTATE;
uint16_t _TRACE_QED_WRITE_TABLE_DSTATE;
uint16_t _TRACE_QED_WRITE_TABLE_CB_DSTATE;
uint16_t _TRACE_QED_NEED_CHECK_TIMER_CB_DSTATE;
uint16_t _TRACE_QED_START_NEED_CHECK_TIMER_DSTATE;
uint16_t _TRACE_QED_CANCEL_NEED_CHECK_TIMER_DSTATE;
uint16_t _TRACE_QED_AIO_COMPLETE_DSTATE;
uint16_t _TRACE_QED_AIO_SETUP_DSTATE;
uint16_t _TRACE_QED_AIO_NEXT_IO_DSTATE;
uint16_t _TRACE_QED_AIO_READ_DATA_DSTATE;
uint16_t _TRACE_QED_AIO_WRITE_DATA_DSTATE;
uint16_t _TRACE_QED_AIO_WRITE_PREFILL_DSTATE;
uint16_t _TRACE_QED_AIO_WRITE_POSTFILL_DSTATE;
uint16_t _TRACE_QED_AIO_WRITE_MAIN_DSTATE;
TraceEvent _TRACE_BDRV_OPEN_COMMON_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "bdrv_open_common",
    .sstate = TRACE_BDRV_OPEN_COMMON_ENABLED,
    .dstate = &_TRACE_BDRV_OPEN_COMMON_DSTATE 
};
TraceEvent _TRACE_BDRV_LOCK_MEDIUM_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "bdrv_lock_medium",
    .sstate = TRACE_BDRV_LOCK_MEDIUM_ENABLED,
    .dstate = &_TRACE_BDRV_LOCK_MEDIUM_DSTATE 
};
TraceEvent _TRACE_BLK_CO_PREADV_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "blk_co_preadv",
    .sstate = TRACE_BLK_CO_PREADV_ENABLED,
    .dstate = &_TRACE_BLK_CO_PREADV_DSTATE 
};
TraceEvent _TRACE_BLK_CO_PWRITEV_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "blk_co_pwritev",
    .sstate = TRACE_BLK_CO_PWRITEV_ENABLED,
    .dstate = &_TRACE_BLK_CO_PWRITEV_DSTATE 
};
TraceEvent _TRACE_BDRV_AIO_FLUSH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "bdrv_aio_flush",
    .sstate = TRACE_BDRV_AIO_FLUSH_ENABLED,
    .dstate = &_TRACE_BDRV_AIO_FLUSH_DSTATE 
};
TraceEvent _TRACE_BDRV_AIO_READV_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "bdrv_aio_readv",
    .sstate = TRACE_BDRV_AIO_READV_ENABLED,
    .dstate = &_TRACE_BDRV_AIO_READV_DSTATE 
};
TraceEvent _TRACE_BDRV_AIO_WRITEV_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "bdrv_aio_writev",
    .sstate = TRACE_BDRV_AIO_WRITEV_ENABLED,
    .dstate = &_TRACE_BDRV_AIO_WRITEV_DSTATE 
};
TraceEvent _TRACE_BDRV_CO_READV_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "bdrv_co_readv",
    .sstate = TRACE_BDRV_CO_READV_ENABLED,
    .dstate = &_TRACE_BDRV_CO_READV_DSTATE 
};
TraceEvent _TRACE_BDRV_CO_WRITEV_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "bdrv_co_writev",
    .sstate = TRACE_BDRV_CO_WRITEV_ENABLED,
    .dstate = &_TRACE_BDRV_CO_WRITEV_DSTATE 
};
TraceEvent _TRACE_BDRV_CO_PWRITE_ZEROES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "bdrv_co_pwrite_zeroes",
    .sstate = TRACE_BDRV_CO_PWRITE_ZEROES_ENABLED,
    .dstate = &_TRACE_BDRV_CO_PWRITE_ZEROES_DSTATE 
};
TraceEvent _TRACE_BDRV_CO_DO_COPY_ON_READV_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "bdrv_co_do_copy_on_readv",
    .sstate = TRACE_BDRV_CO_DO_COPY_ON_READV_ENABLED,
    .dstate = &_TRACE_BDRV_CO_DO_COPY_ON_READV_DSTATE 
};
TraceEvent _TRACE_STREAM_ONE_ITERATION_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "stream_one_iteration",
    .sstate = TRACE_STREAM_ONE_ITERATION_ENABLED,
    .dstate = &_TRACE_STREAM_ONE_ITERATION_DSTATE 
};
TraceEvent _TRACE_STREAM_START_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "stream_start",
    .sstate = TRACE_STREAM_START_ENABLED,
    .dstate = &_TRACE_STREAM_START_DSTATE 
};
TraceEvent _TRACE_COMMIT_ONE_ITERATION_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "commit_one_iteration",
    .sstate = TRACE_COMMIT_ONE_ITERATION_ENABLED,
    .dstate = &_TRACE_COMMIT_ONE_ITERATION_DSTATE 
};
TraceEvent _TRACE_COMMIT_START_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "commit_start",
    .sstate = TRACE_COMMIT_START_ENABLED,
    .dstate = &_TRACE_COMMIT_START_DSTATE 
};
TraceEvent _TRACE_MIRROR_START_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "mirror_start",
    .sstate = TRACE_MIRROR_START_ENABLED,
    .dstate = &_TRACE_MIRROR_START_DSTATE 
};
TraceEvent _TRACE_MIRROR_RESTART_ITER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "mirror_restart_iter",
    .sstate = TRACE_MIRROR_RESTART_ITER_ENABLED,
    .dstate = &_TRACE_MIRROR_RESTART_ITER_DSTATE 
};
TraceEvent _TRACE_MIRROR_BEFORE_FLUSH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "mirror_before_flush",
    .sstate = TRACE_MIRROR_BEFORE_FLUSH_ENABLED,
    .dstate = &_TRACE_MIRROR_BEFORE_FLUSH_DSTATE 
};
TraceEvent _TRACE_MIRROR_BEFORE_DRAIN_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "mirror_before_drain",
    .sstate = TRACE_MIRROR_BEFORE_DRAIN_ENABLED,
    .dstate = &_TRACE_MIRROR_BEFORE_DRAIN_DSTATE 
};
TraceEvent _TRACE_MIRROR_BEFORE_SLEEP_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "mirror_before_sleep",
    .sstate = TRACE_MIRROR_BEFORE_SLEEP_ENABLED,
    .dstate = &_TRACE_MIRROR_BEFORE_SLEEP_DSTATE 
};
TraceEvent _TRACE_MIRROR_ONE_ITERATION_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "mirror_one_iteration",
    .sstate = TRACE_MIRROR_ONE_ITERATION_ENABLED,
    .dstate = &_TRACE_MIRROR_ONE_ITERATION_DSTATE 
};
TraceEvent _TRACE_MIRROR_ITERATION_DONE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "mirror_iteration_done",
    .sstate = TRACE_MIRROR_ITERATION_DONE_ENABLED,
    .dstate = &_TRACE_MIRROR_ITERATION_DONE_DSTATE 
};
TraceEvent _TRACE_MIRROR_YIELD_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "mirror_yield",
    .sstate = TRACE_MIRROR_YIELD_ENABLED,
    .dstate = &_TRACE_MIRROR_YIELD_DSTATE 
};
TraceEvent _TRACE_MIRROR_YIELD_IN_FLIGHT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "mirror_yield_in_flight",
    .sstate = TRACE_MIRROR_YIELD_IN_FLIGHT_ENABLED,
    .dstate = &_TRACE_MIRROR_YIELD_IN_FLIGHT_DSTATE 
};
TraceEvent _TRACE_BACKUP_DO_COW_ENTER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "backup_do_cow_enter",
    .sstate = TRACE_BACKUP_DO_COW_ENTER_ENABLED,
    .dstate = &_TRACE_BACKUP_DO_COW_ENTER_DSTATE 
};
TraceEvent _TRACE_BACKUP_DO_COW_RETURN_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "backup_do_cow_return",
    .sstate = TRACE_BACKUP_DO_COW_RETURN_ENABLED,
    .dstate = &_TRACE_BACKUP_DO_COW_RETURN_DSTATE 
};
TraceEvent _TRACE_BACKUP_DO_COW_SKIP_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "backup_do_cow_skip",
    .sstate = TRACE_BACKUP_DO_COW_SKIP_ENABLED,
    .dstate = &_TRACE_BACKUP_DO_COW_SKIP_DSTATE 
};
TraceEvent _TRACE_BACKUP_DO_COW_PROCESS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "backup_do_cow_process",
    .sstate = TRACE_BACKUP_DO_COW_PROCESS_ENABLED,
    .dstate = &_TRACE_BACKUP_DO_COW_PROCESS_DSTATE 
};
TraceEvent _TRACE_BACKUP_DO_COW_READ_FAIL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "backup_do_cow_read_fail",
    .sstate = TRACE_BACKUP_DO_COW_READ_FAIL_ENABLED,
    .dstate = &_TRACE_BACKUP_DO_COW_READ_FAIL_DSTATE 
};
TraceEvent _TRACE_BACKUP_DO_COW_WRITE_FAIL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "backup_do_cow_write_fail",
    .sstate = TRACE_BACKUP_DO_COW_WRITE_FAIL_ENABLED,
    .dstate = &_TRACE_BACKUP_DO_COW_WRITE_FAIL_DSTATE 
};
TraceEvent _TRACE_QMP_BLOCK_JOB_CANCEL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_block_job_cancel",
    .sstate = TRACE_QMP_BLOCK_JOB_CANCEL_ENABLED,
    .dstate = &_TRACE_QMP_BLOCK_JOB_CANCEL_DSTATE 
};
TraceEvent _TRACE_QMP_BLOCK_JOB_PAUSE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_block_job_pause",
    .sstate = TRACE_QMP_BLOCK_JOB_PAUSE_ENABLED,
    .dstate = &_TRACE_QMP_BLOCK_JOB_PAUSE_DSTATE 
};
TraceEvent _TRACE_QMP_BLOCK_JOB_RESUME_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_block_job_resume",
    .sstate = TRACE_QMP_BLOCK_JOB_RESUME_ENABLED,
    .dstate = &_TRACE_QMP_BLOCK_JOB_RESUME_DSTATE 
};
TraceEvent _TRACE_QMP_BLOCK_JOB_COMPLETE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_block_job_complete",
    .sstate = TRACE_QMP_BLOCK_JOB_COMPLETE_ENABLED,
    .dstate = &_TRACE_QMP_BLOCK_JOB_COMPLETE_DSTATE 
};
TraceEvent _TRACE_QMP_BLOCK_STREAM_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qmp_block_stream",
    .sstate = TRACE_QMP_BLOCK_STREAM_ENABLED,
    .dstate = &_TRACE_QMP_BLOCK_STREAM_DSTATE 
};
TraceEvent _TRACE_PAIO_SUBMIT_CO_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "paio_submit_co",
    .sstate = TRACE_PAIO_SUBMIT_CO_ENABLED,
    .dstate = &_TRACE_PAIO_SUBMIT_CO_DSTATE 
};
TraceEvent _TRACE_PAIO_SUBMIT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "paio_submit",
    .sstate = TRACE_PAIO_SUBMIT_ENABLED,
    .dstate = &_TRACE_PAIO_SUBMIT_DSTATE 
};
TraceEvent _TRACE_QCOW2_WRITEV_START_REQ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_writev_start_req",
    .sstate = TRACE_QCOW2_WRITEV_START_REQ_ENABLED,
    .dstate = &_TRACE_QCOW2_WRITEV_START_REQ_DSTATE 
};
TraceEvent _TRACE_QCOW2_WRITEV_DONE_REQ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_writev_done_req",
    .sstate = TRACE_QCOW2_WRITEV_DONE_REQ_ENABLED,
    .dstate = &_TRACE_QCOW2_WRITEV_DONE_REQ_DSTATE 
};
TraceEvent _TRACE_QCOW2_WRITEV_START_PART_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_writev_start_part",
    .sstate = TRACE_QCOW2_WRITEV_START_PART_ENABLED,
    .dstate = &_TRACE_QCOW2_WRITEV_START_PART_DSTATE 
};
TraceEvent _TRACE_QCOW2_WRITEV_DONE_PART_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_writev_done_part",
    .sstate = TRACE_QCOW2_WRITEV_DONE_PART_ENABLED,
    .dstate = &_TRACE_QCOW2_WRITEV_DONE_PART_DSTATE 
};
TraceEvent _TRACE_QCOW2_WRITEV_DATA_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_writev_data",
    .sstate = TRACE_QCOW2_WRITEV_DATA_ENABLED,
    .dstate = &_TRACE_QCOW2_WRITEV_DATA_DSTATE 
};
TraceEvent _TRACE_QCOW2_PWRITE_ZEROES_START_REQ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_pwrite_zeroes_start_req",
    .sstate = TRACE_QCOW2_PWRITE_ZEROES_START_REQ_ENABLED,
    .dstate = &_TRACE_QCOW2_PWRITE_ZEROES_START_REQ_DSTATE 
};
TraceEvent _TRACE_QCOW2_PWRITE_ZEROES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_pwrite_zeroes",
    .sstate = TRACE_QCOW2_PWRITE_ZEROES_ENABLED,
    .dstate = &_TRACE_QCOW2_PWRITE_ZEROES_DSTATE 
};
TraceEvent _TRACE_QCOW2_ALLOC_CLUSTERS_OFFSET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_alloc_clusters_offset",
    .sstate = TRACE_QCOW2_ALLOC_CLUSTERS_OFFSET_ENABLED,
    .dstate = &_TRACE_QCOW2_ALLOC_CLUSTERS_OFFSET_DSTATE 
};
TraceEvent _TRACE_QCOW2_HANDLE_COPIED_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_handle_copied",
    .sstate = TRACE_QCOW2_HANDLE_COPIED_ENABLED,
    .dstate = &_TRACE_QCOW2_HANDLE_COPIED_DSTATE 
};
TraceEvent _TRACE_QCOW2_HANDLE_ALLOC_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_handle_alloc",
    .sstate = TRACE_QCOW2_HANDLE_ALLOC_ENABLED,
    .dstate = &_TRACE_QCOW2_HANDLE_ALLOC_DSTATE 
};
TraceEvent _TRACE_QCOW2_DO_ALLOC_CLUSTERS_OFFSET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_do_alloc_clusters_offset",
    .sstate = TRACE_QCOW2_DO_ALLOC_CLUSTERS_OFFSET_ENABLED,
    .dstate = &_TRACE_QCOW2_DO_ALLOC_CLUSTERS_OFFSET_DSTATE 
};
TraceEvent _TRACE_QCOW2_CLUSTER_ALLOC_PHYS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_cluster_alloc_phys",
    .sstate = TRACE_QCOW2_CLUSTER_ALLOC_PHYS_ENABLED,
    .dstate = &_TRACE_QCOW2_CLUSTER_ALLOC_PHYS_DSTATE 
};
TraceEvent _TRACE_QCOW2_CLUSTER_LINK_L2_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_cluster_link_l2",
    .sstate = TRACE_QCOW2_CLUSTER_LINK_L2_ENABLED,
    .dstate = &_TRACE_QCOW2_CLUSTER_LINK_L2_DSTATE 
};
TraceEvent _TRACE_QCOW2_L2_ALLOCATE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_l2_allocate",
    .sstate = TRACE_QCOW2_L2_ALLOCATE_ENABLED,
    .dstate = &_TRACE_QCOW2_L2_ALLOCATE_DSTATE 
};
TraceEvent _TRACE_QCOW2_L2_ALLOCATE_GET_EMPTY_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_l2_allocate_get_empty",
    .sstate = TRACE_QCOW2_L2_ALLOCATE_GET_EMPTY_ENABLED,
    .dstate = &_TRACE_QCOW2_L2_ALLOCATE_GET_EMPTY_DSTATE 
};
TraceEvent _TRACE_QCOW2_L2_ALLOCATE_WRITE_L2_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_l2_allocate_write_l2",
    .sstate = TRACE_QCOW2_L2_ALLOCATE_WRITE_L2_ENABLED,
    .dstate = &_TRACE_QCOW2_L2_ALLOCATE_WRITE_L2_DSTATE 
};
TraceEvent _TRACE_QCOW2_L2_ALLOCATE_WRITE_L1_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_l2_allocate_write_l1",
    .sstate = TRACE_QCOW2_L2_ALLOCATE_WRITE_L1_ENABLED,
    .dstate = &_TRACE_QCOW2_L2_ALLOCATE_WRITE_L1_DSTATE 
};
TraceEvent _TRACE_QCOW2_L2_ALLOCATE_DONE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_l2_allocate_done",
    .sstate = TRACE_QCOW2_L2_ALLOCATE_DONE_ENABLED,
    .dstate = &_TRACE_QCOW2_L2_ALLOCATE_DONE_DSTATE 
};
TraceEvent _TRACE_QCOW2_CACHE_GET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_cache_get",
    .sstate = TRACE_QCOW2_CACHE_GET_ENABLED,
    .dstate = &_TRACE_QCOW2_CACHE_GET_DSTATE 
};
TraceEvent _TRACE_QCOW2_CACHE_GET_REPLACE_ENTRY_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_cache_get_replace_entry",
    .sstate = TRACE_QCOW2_CACHE_GET_REPLACE_ENTRY_ENABLED,
    .dstate = &_TRACE_QCOW2_CACHE_GET_REPLACE_ENTRY_DSTATE 
};
TraceEvent _TRACE_QCOW2_CACHE_GET_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_cache_get_read",
    .sstate = TRACE_QCOW2_CACHE_GET_READ_ENABLED,
    .dstate = &_TRACE_QCOW2_CACHE_GET_READ_DSTATE 
};
TraceEvent _TRACE_QCOW2_CACHE_GET_DONE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_cache_get_done",
    .sstate = TRACE_QCOW2_CACHE_GET_DONE_ENABLED,
    .dstate = &_TRACE_QCOW2_CACHE_GET_DONE_DSTATE 
};
TraceEvent _TRACE_QCOW2_CACHE_FLUSH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_cache_flush",
    .sstate = TRACE_QCOW2_CACHE_FLUSH_ENABLED,
    .dstate = &_TRACE_QCOW2_CACHE_FLUSH_DSTATE 
};
TraceEvent _TRACE_QCOW2_CACHE_ENTRY_FLUSH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qcow2_cache_entry_flush",
    .sstate = TRACE_QCOW2_CACHE_ENTRY_FLUSH_ENABLED,
    .dstate = &_TRACE_QCOW2_CACHE_ENTRY_FLUSH_DSTATE 
};
TraceEvent _TRACE_QED_ALLOC_L2_CACHE_ENTRY_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_alloc_l2_cache_entry",
    .sstate = TRACE_QED_ALLOC_L2_CACHE_ENTRY_ENABLED,
    .dstate = &_TRACE_QED_ALLOC_L2_CACHE_ENTRY_DSTATE 
};
TraceEvent _TRACE_QED_UNREF_L2_CACHE_ENTRY_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_unref_l2_cache_entry",
    .sstate = TRACE_QED_UNREF_L2_CACHE_ENTRY_ENABLED,
    .dstate = &_TRACE_QED_UNREF_L2_CACHE_ENTRY_DSTATE 
};
TraceEvent _TRACE_QED_FIND_L2_CACHE_ENTRY_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_find_l2_cache_entry",
    .sstate = TRACE_QED_FIND_L2_CACHE_ENTRY_ENABLED,
    .dstate = &_TRACE_QED_FIND_L2_CACHE_ENTRY_DSTATE 
};
TraceEvent _TRACE_QED_READ_TABLE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_read_table",
    .sstate = TRACE_QED_READ_TABLE_ENABLED,
    .dstate = &_TRACE_QED_READ_TABLE_DSTATE 
};
TraceEvent _TRACE_QED_READ_TABLE_CB_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_read_table_cb",
    .sstate = TRACE_QED_READ_TABLE_CB_ENABLED,
    .dstate = &_TRACE_QED_READ_TABLE_CB_DSTATE 
};
TraceEvent _TRACE_QED_WRITE_TABLE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_write_table",
    .sstate = TRACE_QED_WRITE_TABLE_ENABLED,
    .dstate = &_TRACE_QED_WRITE_TABLE_DSTATE 
};
TraceEvent _TRACE_QED_WRITE_TABLE_CB_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_write_table_cb",
    .sstate = TRACE_QED_WRITE_TABLE_CB_ENABLED,
    .dstate = &_TRACE_QED_WRITE_TABLE_CB_DSTATE 
};
TraceEvent _TRACE_QED_NEED_CHECK_TIMER_CB_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_need_check_timer_cb",
    .sstate = TRACE_QED_NEED_CHECK_TIMER_CB_ENABLED,
    .dstate = &_TRACE_QED_NEED_CHECK_TIMER_CB_DSTATE 
};
TraceEvent _TRACE_QED_START_NEED_CHECK_TIMER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_start_need_check_timer",
    .sstate = TRACE_QED_START_NEED_CHECK_TIMER_ENABLED,
    .dstate = &_TRACE_QED_START_NEED_CHECK_TIMER_DSTATE 
};
TraceEvent _TRACE_QED_CANCEL_NEED_CHECK_TIMER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_cancel_need_check_timer",
    .sstate = TRACE_QED_CANCEL_NEED_CHECK_TIMER_ENABLED,
    .dstate = &_TRACE_QED_CANCEL_NEED_CHECK_TIMER_DSTATE 
};
TraceEvent _TRACE_QED_AIO_COMPLETE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_aio_complete",
    .sstate = TRACE_QED_AIO_COMPLETE_ENABLED,
    .dstate = &_TRACE_QED_AIO_COMPLETE_DSTATE 
};
TraceEvent _TRACE_QED_AIO_SETUP_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_aio_setup",
    .sstate = TRACE_QED_AIO_SETUP_ENABLED,
    .dstate = &_TRACE_QED_AIO_SETUP_DSTATE 
};
TraceEvent _TRACE_QED_AIO_NEXT_IO_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_aio_next_io",
    .sstate = TRACE_QED_AIO_NEXT_IO_ENABLED,
    .dstate = &_TRACE_QED_AIO_NEXT_IO_DSTATE 
};
TraceEvent _TRACE_QED_AIO_READ_DATA_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_aio_read_data",
    .sstate = TRACE_QED_AIO_READ_DATA_ENABLED,
    .dstate = &_TRACE_QED_AIO_READ_DATA_DSTATE 
};
TraceEvent _TRACE_QED_AIO_WRITE_DATA_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_aio_write_data",
    .sstate = TRACE_QED_AIO_WRITE_DATA_ENABLED,
    .dstate = &_TRACE_QED_AIO_WRITE_DATA_DSTATE 
};
TraceEvent _TRACE_QED_AIO_WRITE_PREFILL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_aio_write_prefill",
    .sstate = TRACE_QED_AIO_WRITE_PREFILL_ENABLED,
    .dstate = &_TRACE_QED_AIO_WRITE_PREFILL_DSTATE 
};
TraceEvent _TRACE_QED_AIO_WRITE_POSTFILL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_aio_write_postfill",
    .sstate = TRACE_QED_AIO_WRITE_POSTFILL_ENABLED,
    .dstate = &_TRACE_QED_AIO_WRITE_POSTFILL_DSTATE 
};
TraceEvent _TRACE_QED_AIO_WRITE_MAIN_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "qed_aio_write_main",
    .sstate = TRACE_QED_AIO_WRITE_MAIN_ENABLED,
    .dstate = &_TRACE_QED_AIO_WRITE_MAIN_DSTATE 
};
TraceEvent *block_trace_events[] = {
    &_TRACE_BDRV_OPEN_COMMON_EVENT,
    &_TRACE_BDRV_LOCK_MEDIUM_EVENT,
    &_TRACE_BLK_CO_PREADV_EVENT,
    &_TRACE_BLK_CO_PWRITEV_EVENT,
    &_TRACE_BDRV_AIO_FLUSH_EVENT,
    &_TRACE_BDRV_AIO_READV_EVENT,
    &_TRACE_BDRV_AIO_WRITEV_EVENT,
    &_TRACE_BDRV_CO_READV_EVENT,
    &_TRACE_BDRV_CO_WRITEV_EVENT,
    &_TRACE_BDRV_CO_PWRITE_ZEROES_EVENT,
    &_TRACE_BDRV_CO_DO_COPY_ON_READV_EVENT,
    &_TRACE_STREAM_ONE_ITERATION_EVENT,
    &_TRACE_STREAM_START_EVENT,
    &_TRACE_COMMIT_ONE_ITERATION_EVENT,
    &_TRACE_COMMIT_START_EVENT,
    &_TRACE_MIRROR_START_EVENT,
    &_TRACE_MIRROR_RESTART_ITER_EVENT,
    &_TRACE_MIRROR_BEFORE_FLUSH_EVENT,
    &_TRACE_MIRROR_BEFORE_DRAIN_EVENT,
    &_TRACE_MIRROR_BEFORE_SLEEP_EVENT,
    &_TRACE_MIRROR_ONE_ITERATION_EVENT,
    &_TRACE_MIRROR_ITERATION_DONE_EVENT,
    &_TRACE_MIRROR_YIELD_EVENT,
    &_TRACE_MIRROR_YIELD_IN_FLIGHT_EVENT,
    &_TRACE_BACKUP_DO_COW_ENTER_EVENT,
    &_TRACE_BACKUP_DO_COW_RETURN_EVENT,
    &_TRACE_BACKUP_DO_COW_SKIP_EVENT,
    &_TRACE_BACKUP_DO_COW_PROCESS_EVENT,
    &_TRACE_BACKUP_DO_COW_READ_FAIL_EVENT,
    &_TRACE_BACKUP_DO_COW_WRITE_FAIL_EVENT,
    &_TRACE_QMP_BLOCK_JOB_CANCEL_EVENT,
    &_TRACE_QMP_BLOCK_JOB_PAUSE_EVENT,
    &_TRACE_QMP_BLOCK_JOB_RESUME_EVENT,
    &_TRACE_QMP_BLOCK_JOB_COMPLETE_EVENT,
    &_TRACE_QMP_BLOCK_STREAM_EVENT,
    &_TRACE_PAIO_SUBMIT_CO_EVENT,
    &_TRACE_PAIO_SUBMIT_EVENT,
    &_TRACE_QCOW2_WRITEV_START_REQ_EVENT,
    &_TRACE_QCOW2_WRITEV_DONE_REQ_EVENT,
    &_TRACE_QCOW2_WRITEV_START_PART_EVENT,
    &_TRACE_QCOW2_WRITEV_DONE_PART_EVENT,
    &_TRACE_QCOW2_WRITEV_DATA_EVENT,
    &_TRACE_QCOW2_PWRITE_ZEROES_START_REQ_EVENT,
    &_TRACE_QCOW2_PWRITE_ZEROES_EVENT,
    &_TRACE_QCOW2_ALLOC_CLUSTERS_OFFSET_EVENT,
    &_TRACE_QCOW2_HANDLE_COPIED_EVENT,
    &_TRACE_QCOW2_HANDLE_ALLOC_EVENT,
    &_TRACE_QCOW2_DO_ALLOC_CLUSTERS_OFFSET_EVENT,
    &_TRACE_QCOW2_CLUSTER_ALLOC_PHYS_EVENT,
    &_TRACE_QCOW2_CLUSTER_LINK_L2_EVENT,
    &_TRACE_QCOW2_L2_ALLOCATE_EVENT,
    &_TRACE_QCOW2_L2_ALLOCATE_GET_EMPTY_EVENT,
    &_TRACE_QCOW2_L2_ALLOCATE_WRITE_L2_EVENT,
    &_TRACE_QCOW2_L2_ALLOCATE_WRITE_L1_EVENT,
    &_TRACE_QCOW2_L2_ALLOCATE_DONE_EVENT,
    &_TRACE_QCOW2_CACHE_GET_EVENT,
    &_TRACE_QCOW2_CACHE_GET_REPLACE_ENTRY_EVENT,
    &_TRACE_QCOW2_CACHE_GET_READ_EVENT,
    &_TRACE_QCOW2_CACHE_GET_DONE_EVENT,
    &_TRACE_QCOW2_CACHE_FLUSH_EVENT,
    &_TRACE_QCOW2_CACHE_ENTRY_FLUSH_EVENT,
    &_TRACE_QED_ALLOC_L2_CACHE_ENTRY_EVENT,
    &_TRACE_QED_UNREF_L2_CACHE_ENTRY_EVENT,
    &_TRACE_QED_FIND_L2_CACHE_ENTRY_EVENT,
    &_TRACE_QED_READ_TABLE_EVENT,
    &_TRACE_QED_READ_TABLE_CB_EVENT,
    &_TRACE_QED_WRITE_TABLE_EVENT,
    &_TRACE_QED_WRITE_TABLE_CB_EVENT,
    &_TRACE_QED_NEED_CHECK_TIMER_CB_EVENT,
    &_TRACE_QED_START_NEED_CHECK_TIMER_EVENT,
    &_TRACE_QED_CANCEL_NEED_CHECK_TIMER_EVENT,
    &_TRACE_QED_AIO_COMPLETE_EVENT,
    &_TRACE_QED_AIO_SETUP_EVENT,
    &_TRACE_QED_AIO_NEXT_IO_EVENT,
    &_TRACE_QED_AIO_READ_DATA_EVENT,
    &_TRACE_QED_AIO_WRITE_DATA_EVENT,
    &_TRACE_QED_AIO_WRITE_PREFILL_EVENT,
    &_TRACE_QED_AIO_WRITE_POSTFILL_EVENT,
    &_TRACE_QED_AIO_WRITE_MAIN_EVENT,
  NULL,
};

static void trace_block_register_events(void)
{
    trace_event_register_group(block_trace_events);
}
trace_init(trace_block_register_events)
