/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "trace.h"

uint16_t _TRACE_JAZZIO_READ_DSTATE;
uint16_t _TRACE_JAZZIO_WRITE_DSTATE;
uint16_t _TRACE_RC4030_READ_DSTATE;
uint16_t _TRACE_RC4030_WRITE_DSTATE;
uint16_t _TRACE_LEDMA_MEMORY_READ_DSTATE;
uint16_t _TRACE_LEDMA_MEMORY_WRITE_DSTATE;
uint16_t _TRACE_SPARC32_DMA_SET_IRQ_RAISE_DSTATE;
uint16_t _TRACE_SPARC32_DMA_SET_IRQ_LOWER_DSTATE;
uint16_t _TRACE_ESPDMA_MEMORY_READ_DSTATE;
uint16_t _TRACE_ESPDMA_MEMORY_WRITE_DSTATE;
uint16_t _TRACE_SPARC32_DMA_MEM_READL_DSTATE;
uint16_t _TRACE_SPARC32_DMA_MEM_WRITEL_DSTATE;
uint16_t _TRACE_SPARC32_DMA_ENABLE_RAISE_DSTATE;
uint16_t _TRACE_SPARC32_DMA_ENABLE_LOWER_DSTATE;
uint16_t _TRACE_SUN4M_IOMMU_MEM_READL_DSTATE;
uint16_t _TRACE_SUN4M_IOMMU_MEM_WRITEL_DSTATE;
uint16_t _TRACE_SUN4M_IOMMU_MEM_WRITEL_CTRL_DSTATE;
uint16_t _TRACE_SUN4M_IOMMU_MEM_WRITEL_TLBFLUSH_DSTATE;
uint16_t _TRACE_SUN4M_IOMMU_MEM_WRITEL_PGFLUSH_DSTATE;
uint16_t _TRACE_SUN4M_IOMMU_PAGE_GET_FLAGS_DSTATE;
uint16_t _TRACE_SUN4M_IOMMU_TRANSLATE_PA_DSTATE;
uint16_t _TRACE_SUN4M_IOMMU_BAD_ADDR_DSTATE;
uint16_t _TRACE_I8257_UNREGISTERED_DMA_DSTATE;
TraceEvent _TRACE_JAZZIO_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "jazzio_read",
    .sstate = TRACE_JAZZIO_READ_ENABLED,
    .dstate = &_TRACE_JAZZIO_READ_DSTATE 
};
TraceEvent _TRACE_JAZZIO_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "jazzio_write",
    .sstate = TRACE_JAZZIO_WRITE_ENABLED,
    .dstate = &_TRACE_JAZZIO_WRITE_DSTATE 
};
TraceEvent _TRACE_RC4030_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "rc4030_read",
    .sstate = TRACE_RC4030_READ_ENABLED,
    .dstate = &_TRACE_RC4030_READ_DSTATE 
};
TraceEvent _TRACE_RC4030_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "rc4030_write",
    .sstate = TRACE_RC4030_WRITE_ENABLED,
    .dstate = &_TRACE_RC4030_WRITE_DSTATE 
};
TraceEvent _TRACE_LEDMA_MEMORY_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "ledma_memory_read",
    .sstate = TRACE_LEDMA_MEMORY_READ_ENABLED,
    .dstate = &_TRACE_LEDMA_MEMORY_READ_DSTATE 
};
TraceEvent _TRACE_LEDMA_MEMORY_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "ledma_memory_write",
    .sstate = TRACE_LEDMA_MEMORY_WRITE_ENABLED,
    .dstate = &_TRACE_LEDMA_MEMORY_WRITE_DSTATE 
};
TraceEvent _TRACE_SPARC32_DMA_SET_IRQ_RAISE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sparc32_dma_set_irq_raise",
    .sstate = TRACE_SPARC32_DMA_SET_IRQ_RAISE_ENABLED,
    .dstate = &_TRACE_SPARC32_DMA_SET_IRQ_RAISE_DSTATE 
};
TraceEvent _TRACE_SPARC32_DMA_SET_IRQ_LOWER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sparc32_dma_set_irq_lower",
    .sstate = TRACE_SPARC32_DMA_SET_IRQ_LOWER_ENABLED,
    .dstate = &_TRACE_SPARC32_DMA_SET_IRQ_LOWER_DSTATE 
};
TraceEvent _TRACE_ESPDMA_MEMORY_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "espdma_memory_read",
    .sstate = TRACE_ESPDMA_MEMORY_READ_ENABLED,
    .dstate = &_TRACE_ESPDMA_MEMORY_READ_DSTATE 
};
TraceEvent _TRACE_ESPDMA_MEMORY_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "espdma_memory_write",
    .sstate = TRACE_ESPDMA_MEMORY_WRITE_ENABLED,
    .dstate = &_TRACE_ESPDMA_MEMORY_WRITE_DSTATE 
};
TraceEvent _TRACE_SPARC32_DMA_MEM_READL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sparc32_dma_mem_readl",
    .sstate = TRACE_SPARC32_DMA_MEM_READL_ENABLED,
    .dstate = &_TRACE_SPARC32_DMA_MEM_READL_DSTATE 
};
TraceEvent _TRACE_SPARC32_DMA_MEM_WRITEL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sparc32_dma_mem_writel",
    .sstate = TRACE_SPARC32_DMA_MEM_WRITEL_ENABLED,
    .dstate = &_TRACE_SPARC32_DMA_MEM_WRITEL_DSTATE 
};
TraceEvent _TRACE_SPARC32_DMA_ENABLE_RAISE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sparc32_dma_enable_raise",
    .sstate = TRACE_SPARC32_DMA_ENABLE_RAISE_ENABLED,
    .dstate = &_TRACE_SPARC32_DMA_ENABLE_RAISE_DSTATE 
};
TraceEvent _TRACE_SPARC32_DMA_ENABLE_LOWER_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sparc32_dma_enable_lower",
    .sstate = TRACE_SPARC32_DMA_ENABLE_LOWER_ENABLED,
    .dstate = &_TRACE_SPARC32_DMA_ENABLE_LOWER_DSTATE 
};
TraceEvent _TRACE_SUN4M_IOMMU_MEM_READL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4m_iommu_mem_readl",
    .sstate = TRACE_SUN4M_IOMMU_MEM_READL_ENABLED,
    .dstate = &_TRACE_SUN4M_IOMMU_MEM_READL_DSTATE 
};
TraceEvent _TRACE_SUN4M_IOMMU_MEM_WRITEL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4m_iommu_mem_writel",
    .sstate = TRACE_SUN4M_IOMMU_MEM_WRITEL_ENABLED,
    .dstate = &_TRACE_SUN4M_IOMMU_MEM_WRITEL_DSTATE 
};
TraceEvent _TRACE_SUN4M_IOMMU_MEM_WRITEL_CTRL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4m_iommu_mem_writel_ctrl",
    .sstate = TRACE_SUN4M_IOMMU_MEM_WRITEL_CTRL_ENABLED,
    .dstate = &_TRACE_SUN4M_IOMMU_MEM_WRITEL_CTRL_DSTATE 
};
TraceEvent _TRACE_SUN4M_IOMMU_MEM_WRITEL_TLBFLUSH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4m_iommu_mem_writel_tlbflush",
    .sstate = TRACE_SUN4M_IOMMU_MEM_WRITEL_TLBFLUSH_ENABLED,
    .dstate = &_TRACE_SUN4M_IOMMU_MEM_WRITEL_TLBFLUSH_DSTATE 
};
TraceEvent _TRACE_SUN4M_IOMMU_MEM_WRITEL_PGFLUSH_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4m_iommu_mem_writel_pgflush",
    .sstate = TRACE_SUN4M_IOMMU_MEM_WRITEL_PGFLUSH_ENABLED,
    .dstate = &_TRACE_SUN4M_IOMMU_MEM_WRITEL_PGFLUSH_DSTATE 
};
TraceEvent _TRACE_SUN4M_IOMMU_PAGE_GET_FLAGS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4m_iommu_page_get_flags",
    .sstate = TRACE_SUN4M_IOMMU_PAGE_GET_FLAGS_ENABLED,
    .dstate = &_TRACE_SUN4M_IOMMU_PAGE_GET_FLAGS_DSTATE 
};
TraceEvent _TRACE_SUN4M_IOMMU_TRANSLATE_PA_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4m_iommu_translate_pa",
    .sstate = TRACE_SUN4M_IOMMU_TRANSLATE_PA_ENABLED,
    .dstate = &_TRACE_SUN4M_IOMMU_TRANSLATE_PA_DSTATE 
};
TraceEvent _TRACE_SUN4M_IOMMU_BAD_ADDR_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "sun4m_iommu_bad_addr",
    .sstate = TRACE_SUN4M_IOMMU_BAD_ADDR_ENABLED,
    .dstate = &_TRACE_SUN4M_IOMMU_BAD_ADDR_DSTATE 
};
TraceEvent _TRACE_I8257_UNREGISTERED_DMA_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "i8257_unregistered_dma",
    .sstate = TRACE_I8257_UNREGISTERED_DMA_ENABLED,
    .dstate = &_TRACE_I8257_UNREGISTERED_DMA_DSTATE 
};
TraceEvent *hw_dma_trace_events[] = {
    &_TRACE_JAZZIO_READ_EVENT,
    &_TRACE_JAZZIO_WRITE_EVENT,
    &_TRACE_RC4030_READ_EVENT,
    &_TRACE_RC4030_WRITE_EVENT,
    &_TRACE_LEDMA_MEMORY_READ_EVENT,
    &_TRACE_LEDMA_MEMORY_WRITE_EVENT,
    &_TRACE_SPARC32_DMA_SET_IRQ_RAISE_EVENT,
    &_TRACE_SPARC32_DMA_SET_IRQ_LOWER_EVENT,
    &_TRACE_ESPDMA_MEMORY_READ_EVENT,
    &_TRACE_ESPDMA_MEMORY_WRITE_EVENT,
    &_TRACE_SPARC32_DMA_MEM_READL_EVENT,
    &_TRACE_SPARC32_DMA_MEM_WRITEL_EVENT,
    &_TRACE_SPARC32_DMA_ENABLE_RAISE_EVENT,
    &_TRACE_SPARC32_DMA_ENABLE_LOWER_EVENT,
    &_TRACE_SUN4M_IOMMU_MEM_READL_EVENT,
    &_TRACE_SUN4M_IOMMU_MEM_WRITEL_EVENT,
    &_TRACE_SUN4M_IOMMU_MEM_WRITEL_CTRL_EVENT,
    &_TRACE_SUN4M_IOMMU_MEM_WRITEL_TLBFLUSH_EVENT,
    &_TRACE_SUN4M_IOMMU_MEM_WRITEL_PGFLUSH_EVENT,
    &_TRACE_SUN4M_IOMMU_PAGE_GET_FLAGS_EVENT,
    &_TRACE_SUN4M_IOMMU_TRANSLATE_PA_EVENT,
    &_TRACE_SUN4M_IOMMU_BAD_ADDR_EVENT,
    &_TRACE_I8257_UNREGISTERED_DMA_EVENT,
  NULL,
};

static void trace_hw_dma_register_events(void)
{
    trace_event_register_group(hw_dma_trace_events);
}
trace_init(trace_hw_dma_register_events)
