[package]
name = "hpet"
version = "0.1.0"
authors = ["Zhao Liu <zhao1.liu@intel.com>"]
description = "IA-PC High Precision Event Timer emulation in Rust"

edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
qemu_api = { path = "../../../qemu-api" }
qemu_api_macros = { path = "../../../qemu-api-macros" }

[lints]
workspace = true
