language: cpp
sudo: false
env:
  global:
    - LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/tests/:$TRAVIS_BUILD_DIR:$LD_LIBRARY_PATH
    - DYLD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/tests/:$TRAVIS_BUILD_DIR:$DYLD_LIBRARY_PATH
script:
  - ./make.sh
  - make check
  - cd bindings/python && make check
compiler:
  - clang
  - gcc
os:
  - linux
  - osx
matrix:
  include:
    - if: branch = master
      os: osx
      script: brew update && brew install --HEAD capstone && brew test capstone
      compiler: gcc
    - if: branch = master
      os: osx
      script: brew update && brew install --HEAD capstone && brew test capstone
      compiler: clang
