/* This file is autogenerated by tracetool, do not edit. */

#ifndef TRACE_HW_ALPHA_GENERATED_TRACERS_H
#define TRACE_HW_ALPHA_GENERATED_TRACERS_H

#include "qemu-common.h"
#include "trace/control.h"

extern TraceEvent _TRACE_ALPHA_PCI_IACK_WRITE_EVENT;
extern uint16_t _TRACE_ALPHA_PCI_IACK_WRITE_DSTATE;
#define TRACE_ALPHA_PCI_IACK_WRITE_ENABLED 1
#include "qemu/log.h"


static inline void trace_alpha_pci_iack_write(void)
{
    if (true) {
        if (trace_event_get_state(TRACE_ALPHA_PCI_IACK_WRITE)) {
            struct timeval _now;
            gettimeofday(&_now, NULL);
            qemu_log_mask(LOG_TRACE, "%d@%zd.%06zd:alpha_pci_iack_write " "" "\n",
                          getpid(),
                          (size_t)_now.tv_sec, (size_t)_now.tv_usec
                          );
        }
    }
}
#endif /* TRACE_HW_ALPHA_GENERATED_TRACERS_H */
