#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-2.0-or-later
"""Generate the FEMU device property reference from a built QEMU binary.

The binary is the source of truth: property names, types, defaults and
descriptions come from QMP device-list-properties, and the descriptions are
the ones `-device <type>,help` prints. The topic file
(hw/femu/docs/reference/property-topics.py) only groups properties, lists the
test-only ones and describes the properties a device inherits from a QEMU
parent type.

Usage:
  gen-property-docs.py --qemu build/qemu-system-x86_64           # rewrite docs
  gen-property-docs.py --qemu build/qemu-system-x86_64 --check   # verify only

--check exits 1 when a property has no description or a placeholder one,
when the topic file names a property the binary does not have (or misses one
it has), when the test-only list or the environment variable table is out of
date, or when the committed reference differs from a fresh run.
"""

import argparse
import difflib
import json
import os
import re
import runpy
import subprocess
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__),
                                    "..", "..", ".."))
REF_DIR = os.path.join(ROOT, "hw", "femu", "docs", "reference")
TOPICS = os.path.join(REF_DIR, "property-topics.py")
ENV_INC = os.path.join(REF_DIR, "environment.inc.md")
OUT_STATIC = os.path.join(REF_DIR, "properties.md")
OUT_RUNTIME = os.path.join(REF_DIR, "runtime-properties.md")
SRC_DIR = os.path.join(ROOT, "hw", "femu")

MIN_DESC_CHARS = 25
MIN_DESC_WORDS = 4
PLACEHOLDER = re.compile(r"\b(TODO|TBD|FIXME|XXX)\b|undocumented|^\W*$",
                         re.IGNORECASE)
# Descriptions QEMU attaches to every property of a type; they say nothing
# about what a particular property does.
TYPE_ONLY = {"on/off", "on/off/auto"}
# A property whose name says it carries a unit has to state the unit.
UNIT_NAME = re.compile(r"(_lat|_ns|-ns|_mb|_mbps|_sec$|_size|_pcent|_ppm|"
                       r"^devsz|threshold|limit|stride$|-pages$)")
UNIT_WORD = re.compile(r"\b(ns|MiB|KiB|bytes?|seconds?|percent|pages?|"
                       r"logical blocks|MB/s|per million|reads|sectors?|"
                       r"namespaces|zones|entries|kelvin|cycles|erases)\b|%",
                       re.IGNORECASE)

GENERATED_NOTE = (
    "<!--\n"
    "Generated by hw/femu/scripts/gen-property-docs.py from the built binary.\n"
    "Do not edit by hand: change the description in the code\n"
    "(hw/femu/femu-props.c or hw/femu/cxlssd/props.c) or the topic file\n"
    "(hw/femu/docs/reference/property-topics.py), then run\n"
    "  python3 hw/femu/scripts/gen-property-docs.py --qemu build/qemu-system-x86_64\n"
    "-->\n")


def qmp(qemu, commands, qtest=False):
    """Run QMP commands against a machine-less QEMU and return the results."""
    argv = [qemu, "-machine", "none", "-nodefaults", "-display", "none",
            "-qmp", "stdio"]
    if qtest:
        argv[3:3] = ["-accel", "qtest", "-qtest", "null"]
    seq = [{"execute": "qmp_capabilities"}] + commands + [{"execute": "quit"}]
    text = "".join(json.dumps(c) + "\n" for c in seq)
    proc = subprocess.run(argv, input=text, capture_output=True, text=True,
                          timeout=60)
    replies = []
    for line in proc.stdout.splitlines():
        msg = json.loads(line)
        if "return" in msg or "error" in msg:
            replies.append(msg)
    replies = replies[1:1 + len(commands)]
    if len(replies) != len(commands):
        sys.exit("gen-property-docs: QMP returned %d replies for %d commands"
                 "\n%s" % (len(replies), len(commands), proc.stderr))
    out = []
    for cmd, msg in zip(commands, replies):
        if "error" in msg:
            sys.exit("gen-property-docs: %s %s: %s" % (
                cmd["execute"], cmd.get("arguments"), msg["error"]["desc"]))
        out.append(msg["return"])
    return out


def list_props(qemu, typenames, qtest=False):
    cmds = [{"execute": "device-list-properties",
             "arguments": {"typename": t}} for t in typenames]
    return {t: {p["name"]: p for p in r}
            for t, r in zip(typenames, qmp(qemu, cmds, qtest))}


def list_class_props(qemu, typenames):
    cmds = [{"execute": "qom-list-properties",
             "arguments": {"typename": t}} for t in typenames]
    return {t: {p["name"] for p in r}
            for t, r in zip(typenames, qmp(qemu, cmds))}


def help_text(qemu, typename):
    proc = subprocess.run([qemu, "-device", typename + ",help"],
                          capture_output=True, text=True, timeout=60)
    return proc.stdout


def desc_problem(name, desc):
    """Return why a description is not acceptable, or None."""
    if not desc:
        return "no description"
    d = desc.strip()
    if d in TYPE_ONLY:
        return "only the generic type text %r" % d
    if PLACEHOLDER.search(d):
        return "placeholder text %r" % d
    if len(d) < MIN_DESC_CHARS or len(d.split()) < MIN_DESC_WORDS:
        return "too short (%r): give the meaning, unit and range" % d
    if d.replace("_", " ").lower() == name.replace("_", " ").lower():
        return "repeats the property name"
    if UNIT_NAME.search(name) and not UNIT_WORD.search(d):
        return "names no unit (ns, MiB, bytes, pages, percent, ...)"
    return None


def env_vars_in_code():
    found = {}
    rx = re.compile(r'getenv\("([A-Z0-9_]+)"\)')
    for dirpath, dirnames, filenames in os.walk(SRC_DIR):
        dirnames[:] = [d for d in dirnames if d not in ("tests", "UPSTREAMING")]
        for f in filenames:
            if not f.endswith((".c", ".h")):
                continue
            path = os.path.join(dirpath, f)
            with open(path, errors="replace") as fh:
                for m in rx.finditer(fh.read()):
                    found.setdefault(m.group(1), os.path.relpath(path, ROOT))
    return found


def env_vars_in_doc(text):
    return set(re.findall(r"^\| `([A-Z0-9_]+)` \|", text, re.MULTILINE))


def md_escape(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def fmt_type(prop):
    return "`%s`" % prop.get("type", "?")


def fmt_default(prop):
    if "default-value" not in prop:
        return "unset"
    v = prop["default-value"]
    if isinstance(v, bool):
        return "`on`" if v else "`off`"
    if prop.get("type") == "size" and isinstance(v, int) and v:
        for unit, shift in (("GiB", 30), ("MiB", 20), ("KiB", 10)):
            if v % (1 << shift) == 0:
                return "`%d` (%d %s)" % (v, v >> shift, unit)
    return "`%s`" % v


def plural(n, one, many):
    return "%d %s" % (n, one if n == 1 else many)


def anchor(title):
    a = re.sub(r"[^\w\- ]", "", title.lower()).strip()
    return re.sub(r" ", "-", a)


class Model:
    def __init__(self, qemu, topics):
        self.topics = topics
        devs = topics["devices"]
        types = [d["type"] for d in devs]
        parents = sorted({d["parent"] for d in devs})
        inherits = sorted({d["inherits_from"] for d in devs
                           if d.get("inherits_from")})
        self.props = list_props(qemu, types + inherits)
        self.qtest_props = list_props(qemu, types, qtest=True)
        self.generic = list_class_props(qemu, parents)
        self.help = {t: help_text(qemu, t) for t in types}
        self.errors = []

    def err(self, msg):
        self.errors.append(msg)

    def classify(self, dev):
        t = dev["type"]
        allp = self.props[t]
        generic = self.generic[dev["parent"]]
        inherited = set()
        if dev.get("inherits_from"):
            inherited = set(self.props[dev["inherits_from"]]) - generic
        own = set(allp) - generic - inherited
        test_only = set(self.qtest_props[t]) - set(allp)
        return own, inherited, generic & set(allp), test_only

    def validate(self):
        for dev in self.topics["devices"]:
            t = dev["type"]
            own, inherited, _generic, test_only = self.classify(dev)
            listed = {}
            for topic in dev["topics"]:
                if topic["kind"] not in ("static", "runtime"):
                    self.err("%s: topic %r has kind %r" % (
                        t, topic["title"], topic["kind"]))
                for name in topic["props"]:
                    if name in listed:
                        self.err("%s: %s is in topics %r and %r" % (
                            t, name, listed[name], topic["title"]))
                    listed[name] = topic["title"]
            for name in sorted(own - set(listed)):
                self.err("%s: property %s is in no topic of %s" % (
                    t, name, os.path.relpath(TOPICS, ROOT)))
            for name in sorted(set(listed) - own):
                self.err("%s: topic %r names %s, which the binary does not "
                         "have" % (t, listed[name], name))
            for name in sorted(own):
                why = desc_problem(name, self.props[t][name].get("description"))
                if why:
                    self.err("%s.%s: %s" % (t, name, why))
                    continue
                if not re.search(r"^  %s=\S+\s+- %s" % (
                        re.escape(name),
                        re.escape(self.props[t][name]["description"])),
                        self.help[t], re.MULTILINE):
                    self.err("%s.%s: description missing from -device %s,help"
                             % (t, name, t))
            supp = dev.get("inherited", {})
            for name in sorted(inherited - set(supp)):
                self.err("%s: inherited property %s has no entry under "
                         "\"inherited\"" % (t, name))
            for name in sorted(set(supp) - inherited):
                self.err("%s: \"inherited\" describes %s, which the binary "
                         "does not have" % (t, name))
            for name in sorted(set(supp) & inherited):
                why = desc_problem(name, supp[name])
                if why:
                    self.err("%s.%s (inherited): %s" % (t, name, why))
            want = set(dev.get("test_only", []))
            for name in sorted(test_only - want):
                self.err("%s: qtest-only property %s is not in test_only" % (
                    t, name))
            for name in sorted(want - test_only):
                self.err("%s: test_only lists %s, which is not a qtest-only "
                         "property" % (t, name))

        with open(ENV_INC) as fh:
            documented = env_vars_in_doc(fh.read())
        code = env_vars_in_code()
        for name in sorted(set(code) - documented):
            self.err("environment variable %s (read in %s) is not in %s" % (
                name, code[name], os.path.relpath(ENV_INC, ROOT)))
        for name in sorted(documented - set(code)):
            self.err("%s documents %s, which no file under hw/femu reads" % (
                os.path.relpath(ENV_INC, ROOT), name))

    def table(self, t, names, with_default=True):
        rows = []
        if with_default:
            rows.append("| Property | Type | Default | Description |")
            rows.append("| --- | --- | --- | --- |")
        else:
            rows.append("| Property | Type | Description |")
            rows.append("| --- | --- | --- |")
        for name in names:
            p = self.props[t][name]
            cells = ["`%s`" % name, fmt_type(p)]
            if with_default:
                cells.append(fmt_default(p))
            cells.append(md_escape(p.get("description", "")))
            rows.append("| " + " | ".join(cells) + " |")
        return rows

    def render_static(self):
        out = [GENERATED_NOTE, "# Device property reference", ""]
        out += [
            "Every property of the FEMU devices, as the binary reports it. "
            "`./qemu-system-x86_64 -device femu,help` prints the same "
            "descriptions at the terminal. Properties are set on the command "
            "line, for example `-device femu,femu_mode=1,devsz_mb=4096`, and "
            "only before the device is realized; the QOM properties that can "
            "be read or changed while the guest runs are in "
            "[runtime-properties.md](runtime-properties.md).",
            "",
            "Mode names follow `femu_mode`: OCSSD (0), bbssd (1, black box), "
            "NoSSD (2), ZNS (3), CSD (4) and KV (5). CSD builds the bbssd FTL, "
            "so the bbssd geometry, timing and FTL properties apply to it; KV "
            "uses only the bbssd geometry and NAND timing. Each description "
            "names the modes it applies to.", ""]
        out.append("Devices:")
        out.append("")
        for dev in self.topics["devices"]:
            title = "`%s`: %s" % (dev["type"], dev["title"])
            out.append("- [%s](#%s)" % (title, anchor(title)))
        out.append("- [Test-only properties](#test-only-properties)")
        out.append("- [Environment variables](#environment-variables)")
        out.append("")
        for dev in self.topics["devices"]:
            t = dev["type"]
            own, inherited, generic, _ = self.classify(dev)
            static = [tp for tp in dev["topics"] if tp["kind"] == "static"]
            runtime = [tp for tp in dev["topics"] if tp["kind"] == "runtime"]
            nstatic = sum(len(tp["props"]) for tp in static)
            out.append("## `%s`: %s" % (t, dev["title"]))
            out.append("")
            line = "`-device %s` has %s of its own" % (
                t, plural(nstatic, "property", "properties"))
            if inherited:
                line += ", %d inherited from `%s`" % (
                    len(inherited), dev["inherits_from"])
            if runtime:
                nrt = sum(len(tp["props"]) for tp in runtime)
                line += (" and %s listed in "
                         "[runtime-properties.md](runtime-properties.md)" %
                         plural(nrt, "QOM property", "QOM properties"))
            out.append(line + ".")
            out.append("")
            for tp in static:
                out.append("### %s" % tp["title"])
                out.append("")
                out += self.table(t, tp["props"])
                out.append("")
            if inherited:
                parent = dev["inherits_from"]
                out.append("### Inherited from `%s`" % parent)
                out.append("")
                out.append("These belong to QEMU's `%s` device. The "
                           "descriptions say how `%s` treats them." % (
                               parent, t))
                out.append("")
                out.append("| Property | Type | Default | Description |")
                out.append("| --- | --- | --- | --- |")
                for name in sorted(inherited):
                    p = self.props[t][name]
                    out.append("| `%s` | %s | %s | %s |" % (
                        name, fmt_type(p), fmt_default(p),
                        md_escape(dev.get("inherited", {}).get(name, ""))))
                out.append("")
            shown = sorted(n for n in generic if not n.startswith("x-"))
            hidden = sorted(n for n in generic if n.startswith("x-"))
            if shown:
                kind = ("PCI device" if dev["parent"] == "pci-device"
                        else dev["parent"])
                out.append("### Generic %s properties" % kind)
                out.append("")
                out.append("Common to every QEMU %s and documented by QEMU: "
                           "%s." % (kind, ", ".join("`%s`" % n for n in shown)))
                if hidden:
                    out.append("QEMU's internal compatibility properties "
                               "(%s) are not listed." % ", ".join(
                                   "`%s`" % n for n in hidden))
                out.append("")
        out.append("## Test-only properties")
        out.append("")
        out.append("These exist only when QEMU runs under qtest "
                   "(`-accel qtest`) and serve FEMU's own tests. They are not "
                   "part of the user interface.")
        out.append("")
        for dev in self.topics["devices"]:
            if dev.get("test_only"):
                out.append("- `%s`: %s" % (dev["type"], ", ".join(
                    "`%s`" % n for n in sorted(dev["test_only"]))))
        out.append("")
        with open(ENV_INC) as fh:
            out.append(fh.read().rstrip("\n"))
        out.append("")
        return "\n".join(out)

    def render_runtime(self):
        out = [GENERATED_NOTE, "# Runtime properties and counters", ""]
        out += [
            "QOM properties that a running device exposes. Read and set them "
            "through QMP at `/machine/peripheral/<id>`, where `<id>` is the "
            "`id=` given on `-device`:", "",
            "```",
            '{"execute": "qom-get", "arguments": {"path": '
            '"/machine/peripheral/cxl-ssd0", "property": "read-hits"}}',
            '{"execute": "qom-set", "arguments": {"path": '
            '"/machine/peripheral/cxl-ssd0", "property": "stats-reset", '
            '"value": true}}',
            "```", "",
            "or in the HMP monitor with `qom-get` and `qom-set`. Event counters "
            "are cleared by `stats-reset`; gauges and totals keep their value. "
            "Descriptions are the ones `-device <type>,help` prints.", ""]
        for dev in self.topics["devices"]:
            runtime = [tp for tp in dev["topics"] if tp["kind"] == "runtime"]
            if not runtime:
                continue
            t = dev["type"]
            out.append("## `%s`: %s" % (t, dev["title"]))
            out.append("")
            for tp in runtime:
                out.append("### %s" % tp["title"])
                out.append("")
                out += self.table(t, tp["props"], with_default=False)
                out.append("")
        return "\n".join(out)


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--qemu", required=True, help="built qemu-system-x86_64")
    ap.add_argument("--check", action="store_true",
                    help="verify descriptions and the committed files only")
    args = ap.parse_args()

    topics = {"devices": runpy.run_path(TOPICS)["DEVICES"]}
    model = Model(args.qemu, topics)
    model.validate()

    outputs = {OUT_STATIC: model.render_static(),
               OUT_RUNTIME: model.render_runtime()}
    if args.check:
        for path, text in outputs.items():
            try:
                with open(path) as fh:
                    old = fh.read()
            except OSError:
                old = ""
            if old != text:
                rel = os.path.relpath(path, ROOT)
                diff = list(difflib.unified_diff(
                    old.splitlines(), text.splitlines(), "committed/" + rel,
                    "generated/" + rel, lineterm="", n=1))
                model.err("%s is out of date; regenerate it:\n  %s" % (
                    rel, "\n  ".join(diff[:20])))
    else:
        for path, text in outputs.items():
            with open(path, "w") as fh:
                fh.write(text)

    for e in model.errors:
        print("gen-property-docs: " + e, file=sys.stderr)
    counts = []
    for dev in topics["devices"]:
        own, inherited, _, _ = model.classify(dev)
        counts.append("%s %d own%s" % (dev["type"], len(own),
                      " + %d inherited" % len(inherited) if inherited else ""))
    print("gen-property-docs: %s; %d problem(s)" % (
        ", ".join(counts), len(model.errors)), file=sys.stderr)
    return 1 if model.errors else 0


if __name__ == "__main__":
    sys.exit(main())
