name: Lint

concurrency:
  group: lint-${{ github.head_ref }}
  cancel-in-progress: true

on:
  push:
    paths:
    - "**.py"
    - ".github/workflows/lint.yml"
  pull_request:
    paths:
    - "**.py"
    - ".github/workflows/lint.yml"

jobs:

  pylint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python -m pip install pylint
    - run: pylint mesonbuild

  mypy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - run: python -m pip install mypy
    - run: python run_mypy.py
