/* This file is autogenerated by tracetool, do not edit. */

#include "qemu/osdep.h"
#include "trace.h"

uint16_t _TRACE_X86_IOMMU_IEC_NOTIFY_DSTATE;
uint16_t _TRACE_VTD_SWITCH_ADDRESS_SPACE_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_INVALID_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_CC_DOMAIN_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_CC_GLOBAL_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_CC_DEVICE_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_CC_DEVICES_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_CC_INVALID_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_IOTLB_GLOBAL_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_IOTLB_DOMAIN_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_IOTLB_PAGES_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_IOTLB_INVALID_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_WAIT_SW_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_WAIT_IRQ_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_WAIT_INVALID_DSTATE;
uint16_t _TRACE_VTD_INV_DESC_WAIT_WRITE_FAIL_DSTATE;
uint16_t _TRACE_VTD_RE_NOT_PRESENT_DSTATE;
uint16_t _TRACE_VTD_RE_INVALID_DSTATE;
uint16_t _TRACE_VTD_CE_NOT_PRESENT_DSTATE;
uint16_t _TRACE_VTD_CE_INVALID_DSTATE;
uint16_t _TRACE_VTD_IOTLB_PAGE_HIT_DSTATE;
uint16_t _TRACE_VTD_IOTLB_PAGE_UPDATE_DSTATE;
uint16_t _TRACE_VTD_IOTLB_CC_HIT_DSTATE;
uint16_t _TRACE_VTD_IOTLB_CC_UPDATE_DSTATE;
uint16_t _TRACE_VTD_IOTLB_RESET_DSTATE;
uint16_t _TRACE_VTD_FAULT_DISABLED_DSTATE;
uint16_t _TRACE_AMDVI_EVNTLOG_FAIL_DSTATE;
uint16_t _TRACE_AMDVI_CACHE_UPDATE_DSTATE;
uint16_t _TRACE_AMDVI_COMPLETION_WAIT_FAIL_DSTATE;
uint16_t _TRACE_AMDVI_MMIO_WRITE_DSTATE;
uint16_t _TRACE_AMDVI_MMIO_READ_DSTATE;
uint16_t _TRACE_AMDVI_MMIO_READ_INVALID_DSTATE;
uint16_t _TRACE_AMDVI_COMMAND_ERROR_DSTATE;
uint16_t _TRACE_AMDVI_COMMAND_READ_FAIL_DSTATE;
uint16_t _TRACE_AMDVI_COMMAND_EXEC_DSTATE;
uint16_t _TRACE_AMDVI_UNHANDLED_COMMAND_DSTATE;
uint16_t _TRACE_AMDVI_INTR_INVAL_DSTATE;
uint16_t _TRACE_AMDVI_IOTLB_INVAL_DSTATE;
uint16_t _TRACE_AMDVI_PREFETCH_PAGES_DSTATE;
uint16_t _TRACE_AMDVI_PAGES_INVAL_DSTATE;
uint16_t _TRACE_AMDVI_ALL_INVAL_DSTATE;
uint16_t _TRACE_AMDVI_PPR_EXEC_DSTATE;
uint16_t _TRACE_AMDVI_DEVTAB_INVAL_DSTATE;
uint16_t _TRACE_AMDVI_COMPLETION_WAIT_DSTATE;
uint16_t _TRACE_AMDVI_CONTROL_STATUS_DSTATE;
uint16_t _TRACE_AMDVI_IOTLB_RESET_DSTATE;
uint16_t _TRACE_AMDVI_DTE_GET_FAIL_DSTATE;
uint16_t _TRACE_AMDVI_INVALID_DTE_DSTATE;
uint16_t _TRACE_AMDVI_GET_PTE_HWERROR_DSTATE;
uint16_t _TRACE_AMDVI_MODE_INVALID_DSTATE;
uint16_t _TRACE_AMDVI_PAGE_FAULT_DSTATE;
uint16_t _TRACE_AMDVI_IOTLB_HIT_DSTATE;
uint16_t _TRACE_AMDVI_TRANSLATION_RESULT_DSTATE;
TraceEvent _TRACE_X86_IOMMU_IEC_NOTIFY_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "x86_iommu_iec_notify",
    .sstate = TRACE_X86_IOMMU_IEC_NOTIFY_ENABLED,
    .dstate = &_TRACE_X86_IOMMU_IEC_NOTIFY_DSTATE 
};
TraceEvent _TRACE_VTD_SWITCH_ADDRESS_SPACE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_switch_address_space",
    .sstate = TRACE_VTD_SWITCH_ADDRESS_SPACE_ENABLED,
    .dstate = &_TRACE_VTD_SWITCH_ADDRESS_SPACE_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc",
    .sstate = TRACE_VTD_INV_DESC_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_INVALID_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_invalid",
    .sstate = TRACE_VTD_INV_DESC_INVALID_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_INVALID_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_CC_DOMAIN_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_cc_domain",
    .sstate = TRACE_VTD_INV_DESC_CC_DOMAIN_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_CC_DOMAIN_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_CC_GLOBAL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_cc_global",
    .sstate = TRACE_VTD_INV_DESC_CC_GLOBAL_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_CC_GLOBAL_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_CC_DEVICE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_cc_device",
    .sstate = TRACE_VTD_INV_DESC_CC_DEVICE_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_CC_DEVICE_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_CC_DEVICES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_cc_devices",
    .sstate = TRACE_VTD_INV_DESC_CC_DEVICES_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_CC_DEVICES_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_CC_INVALID_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_cc_invalid",
    .sstate = TRACE_VTD_INV_DESC_CC_INVALID_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_CC_INVALID_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_IOTLB_GLOBAL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_iotlb_global",
    .sstate = TRACE_VTD_INV_DESC_IOTLB_GLOBAL_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_IOTLB_GLOBAL_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_IOTLB_DOMAIN_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_iotlb_domain",
    .sstate = TRACE_VTD_INV_DESC_IOTLB_DOMAIN_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_IOTLB_DOMAIN_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_IOTLB_PAGES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_iotlb_pages",
    .sstate = TRACE_VTD_INV_DESC_IOTLB_PAGES_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_IOTLB_PAGES_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_IOTLB_INVALID_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_iotlb_invalid",
    .sstate = TRACE_VTD_INV_DESC_IOTLB_INVALID_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_IOTLB_INVALID_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_WAIT_SW_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_wait_sw",
    .sstate = TRACE_VTD_INV_DESC_WAIT_SW_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_WAIT_SW_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_WAIT_IRQ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_wait_irq",
    .sstate = TRACE_VTD_INV_DESC_WAIT_IRQ_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_WAIT_IRQ_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_WAIT_INVALID_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_wait_invalid",
    .sstate = TRACE_VTD_INV_DESC_WAIT_INVALID_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_WAIT_INVALID_DSTATE 
};
TraceEvent _TRACE_VTD_INV_DESC_WAIT_WRITE_FAIL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_inv_desc_wait_write_fail",
    .sstate = TRACE_VTD_INV_DESC_WAIT_WRITE_FAIL_ENABLED,
    .dstate = &_TRACE_VTD_INV_DESC_WAIT_WRITE_FAIL_DSTATE 
};
TraceEvent _TRACE_VTD_RE_NOT_PRESENT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_re_not_present",
    .sstate = TRACE_VTD_RE_NOT_PRESENT_ENABLED,
    .dstate = &_TRACE_VTD_RE_NOT_PRESENT_DSTATE 
};
TraceEvent _TRACE_VTD_RE_INVALID_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_re_invalid",
    .sstate = TRACE_VTD_RE_INVALID_ENABLED,
    .dstate = &_TRACE_VTD_RE_INVALID_DSTATE 
};
TraceEvent _TRACE_VTD_CE_NOT_PRESENT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_ce_not_present",
    .sstate = TRACE_VTD_CE_NOT_PRESENT_ENABLED,
    .dstate = &_TRACE_VTD_CE_NOT_PRESENT_DSTATE 
};
TraceEvent _TRACE_VTD_CE_INVALID_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_ce_invalid",
    .sstate = TRACE_VTD_CE_INVALID_ENABLED,
    .dstate = &_TRACE_VTD_CE_INVALID_DSTATE 
};
TraceEvent _TRACE_VTD_IOTLB_PAGE_HIT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_iotlb_page_hit",
    .sstate = TRACE_VTD_IOTLB_PAGE_HIT_ENABLED,
    .dstate = &_TRACE_VTD_IOTLB_PAGE_HIT_DSTATE 
};
TraceEvent _TRACE_VTD_IOTLB_PAGE_UPDATE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_iotlb_page_update",
    .sstate = TRACE_VTD_IOTLB_PAGE_UPDATE_ENABLED,
    .dstate = &_TRACE_VTD_IOTLB_PAGE_UPDATE_DSTATE 
};
TraceEvent _TRACE_VTD_IOTLB_CC_HIT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_iotlb_cc_hit",
    .sstate = TRACE_VTD_IOTLB_CC_HIT_ENABLED,
    .dstate = &_TRACE_VTD_IOTLB_CC_HIT_DSTATE 
};
TraceEvent _TRACE_VTD_IOTLB_CC_UPDATE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_iotlb_cc_update",
    .sstate = TRACE_VTD_IOTLB_CC_UPDATE_ENABLED,
    .dstate = &_TRACE_VTD_IOTLB_CC_UPDATE_DSTATE 
};
TraceEvent _TRACE_VTD_IOTLB_RESET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_iotlb_reset",
    .sstate = TRACE_VTD_IOTLB_RESET_ENABLED,
    .dstate = &_TRACE_VTD_IOTLB_RESET_DSTATE 
};
TraceEvent _TRACE_VTD_FAULT_DISABLED_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "vtd_fault_disabled",
    .sstate = TRACE_VTD_FAULT_DISABLED_ENABLED,
    .dstate = &_TRACE_VTD_FAULT_DISABLED_DSTATE 
};
TraceEvent _TRACE_AMDVI_EVNTLOG_FAIL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_evntlog_fail",
    .sstate = TRACE_AMDVI_EVNTLOG_FAIL_ENABLED,
    .dstate = &_TRACE_AMDVI_EVNTLOG_FAIL_DSTATE 
};
TraceEvent _TRACE_AMDVI_CACHE_UPDATE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_cache_update",
    .sstate = TRACE_AMDVI_CACHE_UPDATE_ENABLED,
    .dstate = &_TRACE_AMDVI_CACHE_UPDATE_DSTATE 
};
TraceEvent _TRACE_AMDVI_COMPLETION_WAIT_FAIL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_completion_wait_fail",
    .sstate = TRACE_AMDVI_COMPLETION_WAIT_FAIL_ENABLED,
    .dstate = &_TRACE_AMDVI_COMPLETION_WAIT_FAIL_DSTATE 
};
TraceEvent _TRACE_AMDVI_MMIO_WRITE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_mmio_write",
    .sstate = TRACE_AMDVI_MMIO_WRITE_ENABLED,
    .dstate = &_TRACE_AMDVI_MMIO_WRITE_DSTATE 
};
TraceEvent _TRACE_AMDVI_MMIO_READ_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_mmio_read",
    .sstate = TRACE_AMDVI_MMIO_READ_ENABLED,
    .dstate = &_TRACE_AMDVI_MMIO_READ_DSTATE 
};
TraceEvent _TRACE_AMDVI_MMIO_READ_INVALID_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_mmio_read_invalid",
    .sstate = TRACE_AMDVI_MMIO_READ_INVALID_ENABLED,
    .dstate = &_TRACE_AMDVI_MMIO_READ_INVALID_DSTATE 
};
TraceEvent _TRACE_AMDVI_COMMAND_ERROR_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_command_error",
    .sstate = TRACE_AMDVI_COMMAND_ERROR_ENABLED,
    .dstate = &_TRACE_AMDVI_COMMAND_ERROR_DSTATE 
};
TraceEvent _TRACE_AMDVI_COMMAND_READ_FAIL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_command_read_fail",
    .sstate = TRACE_AMDVI_COMMAND_READ_FAIL_ENABLED,
    .dstate = &_TRACE_AMDVI_COMMAND_READ_FAIL_DSTATE 
};
TraceEvent _TRACE_AMDVI_COMMAND_EXEC_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_command_exec",
    .sstate = TRACE_AMDVI_COMMAND_EXEC_ENABLED,
    .dstate = &_TRACE_AMDVI_COMMAND_EXEC_DSTATE 
};
TraceEvent _TRACE_AMDVI_UNHANDLED_COMMAND_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_unhandled_command",
    .sstate = TRACE_AMDVI_UNHANDLED_COMMAND_ENABLED,
    .dstate = &_TRACE_AMDVI_UNHANDLED_COMMAND_DSTATE 
};
TraceEvent _TRACE_AMDVI_INTR_INVAL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_intr_inval",
    .sstate = TRACE_AMDVI_INTR_INVAL_ENABLED,
    .dstate = &_TRACE_AMDVI_INTR_INVAL_DSTATE 
};
TraceEvent _TRACE_AMDVI_IOTLB_INVAL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_iotlb_inval",
    .sstate = TRACE_AMDVI_IOTLB_INVAL_ENABLED,
    .dstate = &_TRACE_AMDVI_IOTLB_INVAL_DSTATE 
};
TraceEvent _TRACE_AMDVI_PREFETCH_PAGES_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_prefetch_pages",
    .sstate = TRACE_AMDVI_PREFETCH_PAGES_ENABLED,
    .dstate = &_TRACE_AMDVI_PREFETCH_PAGES_DSTATE 
};
TraceEvent _TRACE_AMDVI_PAGES_INVAL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_pages_inval",
    .sstate = TRACE_AMDVI_PAGES_INVAL_ENABLED,
    .dstate = &_TRACE_AMDVI_PAGES_INVAL_DSTATE 
};
TraceEvent _TRACE_AMDVI_ALL_INVAL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_all_inval",
    .sstate = TRACE_AMDVI_ALL_INVAL_ENABLED,
    .dstate = &_TRACE_AMDVI_ALL_INVAL_DSTATE 
};
TraceEvent _TRACE_AMDVI_PPR_EXEC_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_ppr_exec",
    .sstate = TRACE_AMDVI_PPR_EXEC_ENABLED,
    .dstate = &_TRACE_AMDVI_PPR_EXEC_DSTATE 
};
TraceEvent _TRACE_AMDVI_DEVTAB_INVAL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_devtab_inval",
    .sstate = TRACE_AMDVI_DEVTAB_INVAL_ENABLED,
    .dstate = &_TRACE_AMDVI_DEVTAB_INVAL_DSTATE 
};
TraceEvent _TRACE_AMDVI_COMPLETION_WAIT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_completion_wait",
    .sstate = TRACE_AMDVI_COMPLETION_WAIT_ENABLED,
    .dstate = &_TRACE_AMDVI_COMPLETION_WAIT_DSTATE 
};
TraceEvent _TRACE_AMDVI_CONTROL_STATUS_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_control_status",
    .sstate = TRACE_AMDVI_CONTROL_STATUS_ENABLED,
    .dstate = &_TRACE_AMDVI_CONTROL_STATUS_DSTATE 
};
TraceEvent _TRACE_AMDVI_IOTLB_RESET_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_iotlb_reset",
    .sstate = TRACE_AMDVI_IOTLB_RESET_ENABLED,
    .dstate = &_TRACE_AMDVI_IOTLB_RESET_DSTATE 
};
TraceEvent _TRACE_AMDVI_DTE_GET_FAIL_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_dte_get_fail",
    .sstate = TRACE_AMDVI_DTE_GET_FAIL_ENABLED,
    .dstate = &_TRACE_AMDVI_DTE_GET_FAIL_DSTATE 
};
TraceEvent _TRACE_AMDVI_INVALID_DTE_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_invalid_dte",
    .sstate = TRACE_AMDVI_INVALID_DTE_ENABLED,
    .dstate = &_TRACE_AMDVI_INVALID_DTE_DSTATE 
};
TraceEvent _TRACE_AMDVI_GET_PTE_HWERROR_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_get_pte_hwerror",
    .sstate = TRACE_AMDVI_GET_PTE_HWERROR_ENABLED,
    .dstate = &_TRACE_AMDVI_GET_PTE_HWERROR_DSTATE 
};
TraceEvent _TRACE_AMDVI_MODE_INVALID_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_mode_invalid",
    .sstate = TRACE_AMDVI_MODE_INVALID_ENABLED,
    .dstate = &_TRACE_AMDVI_MODE_INVALID_DSTATE 
};
TraceEvent _TRACE_AMDVI_PAGE_FAULT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_page_fault",
    .sstate = TRACE_AMDVI_PAGE_FAULT_ENABLED,
    .dstate = &_TRACE_AMDVI_PAGE_FAULT_DSTATE 
};
TraceEvent _TRACE_AMDVI_IOTLB_HIT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_iotlb_hit",
    .sstate = TRACE_AMDVI_IOTLB_HIT_ENABLED,
    .dstate = &_TRACE_AMDVI_IOTLB_HIT_DSTATE 
};
TraceEvent _TRACE_AMDVI_TRANSLATION_RESULT_EVENT = {
    .id = 0,
    .vcpu_id = TRACE_VCPU_EVENT_NONE,
    .name = "amdvi_translation_result",
    .sstate = TRACE_AMDVI_TRANSLATION_RESULT_ENABLED,
    .dstate = &_TRACE_AMDVI_TRANSLATION_RESULT_DSTATE 
};
TraceEvent *hw_i386_trace_events[] = {
    &_TRACE_X86_IOMMU_IEC_NOTIFY_EVENT,
    &_TRACE_VTD_SWITCH_ADDRESS_SPACE_EVENT,
    &_TRACE_VTD_INV_DESC_EVENT,
    &_TRACE_VTD_INV_DESC_INVALID_EVENT,
    &_TRACE_VTD_INV_DESC_CC_DOMAIN_EVENT,
    &_TRACE_VTD_INV_DESC_CC_GLOBAL_EVENT,
    &_TRACE_VTD_INV_DESC_CC_DEVICE_EVENT,
    &_TRACE_VTD_INV_DESC_CC_DEVICES_EVENT,
    &_TRACE_VTD_INV_DESC_CC_INVALID_EVENT,
    &_TRACE_VTD_INV_DESC_IOTLB_GLOBAL_EVENT,
    &_TRACE_VTD_INV_DESC_IOTLB_DOMAIN_EVENT,
    &_TRACE_VTD_INV_DESC_IOTLB_PAGES_EVENT,
    &_TRACE_VTD_INV_DESC_IOTLB_INVALID_EVENT,
    &_TRACE_VTD_INV_DESC_WAIT_SW_EVENT,
    &_TRACE_VTD_INV_DESC_WAIT_IRQ_EVENT,
    &_TRACE_VTD_INV_DESC_WAIT_INVALID_EVENT,
    &_TRACE_VTD_INV_DESC_WAIT_WRITE_FAIL_EVENT,
    &_TRACE_VTD_RE_NOT_PRESENT_EVENT,
    &_TRACE_VTD_RE_INVALID_EVENT,
    &_TRACE_VTD_CE_NOT_PRESENT_EVENT,
    &_TRACE_VTD_CE_INVALID_EVENT,
    &_TRACE_VTD_IOTLB_PAGE_HIT_EVENT,
    &_TRACE_VTD_IOTLB_PAGE_UPDATE_EVENT,
    &_TRACE_VTD_IOTLB_CC_HIT_EVENT,
    &_TRACE_VTD_IOTLB_CC_UPDATE_EVENT,
    &_TRACE_VTD_IOTLB_RESET_EVENT,
    &_TRACE_VTD_FAULT_DISABLED_EVENT,
    &_TRACE_AMDVI_EVNTLOG_FAIL_EVENT,
    &_TRACE_AMDVI_CACHE_UPDATE_EVENT,
    &_TRACE_AMDVI_COMPLETION_WAIT_FAIL_EVENT,
    &_TRACE_AMDVI_MMIO_WRITE_EVENT,
    &_TRACE_AMDVI_MMIO_READ_EVENT,
    &_TRACE_AMDVI_MMIO_READ_INVALID_EVENT,
    &_TRACE_AMDVI_COMMAND_ERROR_EVENT,
    &_TRACE_AMDVI_COMMAND_READ_FAIL_EVENT,
    &_TRACE_AMDVI_COMMAND_EXEC_EVENT,
    &_TRACE_AMDVI_UNHANDLED_COMMAND_EVENT,
    &_TRACE_AMDVI_INTR_INVAL_EVENT,
    &_TRACE_AMDVI_IOTLB_INVAL_EVENT,
    &_TRACE_AMDVI_PREFETCH_PAGES_EVENT,
    &_TRACE_AMDVI_PAGES_INVAL_EVENT,
    &_TRACE_AMDVI_ALL_INVAL_EVENT,
    &_TRACE_AMDVI_PPR_EXEC_EVENT,
    &_TRACE_AMDVI_DEVTAB_INVAL_EVENT,
    &_TRACE_AMDVI_COMPLETION_WAIT_EVENT,
    &_TRACE_AMDVI_CONTROL_STATUS_EVENT,
    &_TRACE_AMDVI_IOTLB_RESET_EVENT,
    &_TRACE_AMDVI_DTE_GET_FAIL_EVENT,
    &_TRACE_AMDVI_INVALID_DTE_EVENT,
    &_TRACE_AMDVI_GET_PTE_HWERROR_EVENT,
    &_TRACE_AMDVI_MODE_INVALID_EVENT,
    &_TRACE_AMDVI_PAGE_FAULT_EVENT,
    &_TRACE_AMDVI_IOTLB_HIT_EVENT,
    &_TRACE_AMDVI_TRANSLATION_RESULT_EVENT,
  NULL,
};

static void trace_hw_i386_register_events(void)
{
    trace_event_register_group(hw_i386_trace_events);
}
trace_init(trace_hw_i386_register_events)
